### ISSUE TITLE
Write Release process SOP

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#1004]
As a developer, I want to have a document with the description of the release process.

Helper documents: https://docs.google.com/document/d/1PnO7EpIWwgB_nyZ51TYzJOkwJiFwtYLBqse2jDK91ko/edit?usp=sharing

**Comment by zperova** [comment]
@mauroz77 is this done? could you please include the link to the actual document here and close the issue if so? thank you.

**Comment by mauroz77** [comment]
@zperova proposed document: https://docs.google.com/document/d/1cXB9tGF-Xo1DxVUL_WmcoiC7EIUBJ0YSXYN32EJ2n_8/edit?usp=sharing

**Comment by zperova** [comment]
great, thanks!
