### ISSUE TITLE
Fetch molecular data for models from CMP

### ISSUE THREAD

**Issue by Mandloi2309** [PDXFinder/pdxfinder#1015]
### Description

As a bioinformatician, I want to acquire new models and their molecular data from Cell models passport.

### Acceptance criteria

- [x] CNV data
- [x] Expression data
- [x] Mutation data

**Comment by Mandloi2309** [comment]
There is data on methylation and proteomics which could be ingested on a later stage

**Comment by zperova** [comment]
@Mandloi2309 could you please create a ticket for the remaining data in Product backlog and close this issue if done? thank you!

**Comment by Mandloi2309** [comment]
Done https://app.zenhub.com/workspaces/pdcmfinder-board-5f0f036188f27e0014a7bdfc/issues/pdcmfinder/pdxfinder/1031
