### ISSUE TITLE
Prepare data requested via Helpdesk

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1017]
### Description

As a developer, I want to provide the requested data to the user in the absence of API documentation.

### Acceptance criteria

- [x] requested data prepared as a csv

**Comment by ficolo** [comment]
List of all xenografts with expression data and patient treatmetn: https://www.cancermodels.org/api/search_index?&dataset_available=ov.{%22expression%22,%22patient%20treatment%22}&model_type=in.(%22xenograft%22)&limit=10&offset=0&select=patient_age,patient_sex,external_model_id,model_type,data_source,histology,primary_site,collection_site,tumour_type,dataset_available&order=model_dataset_type_count.desc.nullslast

Example of patient treatment API call: https://www.cancermodels.org/api/patient_treatment?model_id=eq.575525617672&select=*

Example of expression data API call: https://www.cancermodels.org/api/expression_data_table?molecular_characterization_id=eq.1589137899524&limit=10&offset=0

**Comment by Mandloi2309** [comment]
Data hosted on drive: https://drive.google.com/drive/folders/1_xYv8EHBbvfSfLXYf0OoCxtFBKI-7BBg?usp=sharing
