### ISSUE TITLE
Documentation for public API

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1030]
### Description

As a developer, I want to have comprehensive and up-to-date documentation for PDCM Finder public API to ensure programmatic access to the data for our users.

### Acceptance criteria

- [x] test documentation with a user of the PDCM Finder API
- [x] link to comprehensive documentation is provided on the cancermodels.org website

**Comment by mauroz77** [comment]
@zperova I haven't seen any feedback regarding this. Should we mark it as done?

**Comment by mauroz77** [comment]
@zperova done
