### ISSUE TITLE
Troubleshooting guide for the release process

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1034]
### Description

As a developer, I want to have documented examples of common errors that arise during release and how to troubleshoot them to ensure smooth future releases.

### Acceptance criteria

- [x] troubleshooting guide in in the SOP folder in Google drive

**Comment by zperova** [comment]
@mauroz77 @Mandloi2309 could you please let me know what is the status of this ticket?

**Comment by mauroz77** [comment]
https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=156441793#RunningPDCMETLontheEBIcluster(Codon)-Troubleshooting has a troubleshooting section focused on running the ETL in the cluster. It's not clear to me if this ticket aims to have troubleshooting documentation for the whole release process, in which case the information could go https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/PDCM+Data+Release+Process or in a separated page.

**Comment by zperova** [comment]
@mauroz77 this is for having troubleshooting documentation for the whole release process. please include this and the rest of troubleshooting steps in the Release document so that everything is in one location. thank you!

**Comment by zperova** [comment]
@mauroz77 please add the Troubleshooting part to the end of the Release document here: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/PDCM+Data+Release+Process

**Comment by mauroz77** [comment]
@zperova done
