### ISSUE TITLE
PDMR CNA and expression data

### ISSUE THREAD

**Issue by Mandloi2309** [PDXFinder/pdxfinder#1035]
### Description

As a bioinformatician, I want to extract molecular data from PDMR data dump.

### Acceptance criteria

- [x] Extraction of cna and expression data from oracle dump

**Comment by Mandloi2309** [comment]
CNA data needs to be requested. Expression data extracted and annotation done

**Comment by zperova** [comment]
@Mandloi2309 could you please make a ticket for CNA data and close this one if done? thank you!
