### ISSUE TITLE
Data flow diagram and documentation

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1042]
### Description

As a developer, I want to document data flow to improve training materials for PDCM Finder.

### Acceptance criteria

- [x] make a diagram reflects the current data flow of PDCM metadata and data
- [ ] write supporting documentation

**Comment by Mandloi2309** [comment]
https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Data+Integration+Proccess
