### ISSUE TITLE
Model MI compliance score 

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1043]
### Description

As a developer, I want to implement a scoring system for PDCM models based on the number of fields with valuable input to have a better way to present search results for the user on the portal.

Ideas for how this might work

- assign a point for each attribute that has a useful value 
- subtract a point for each field where value is Not provided or Not collected
- assign a score based on the relative value of attributes
- sort models based on the MI compliance score

### Acceptance criteria

- [x] devise a calculation for the compliance score - ZP
- [x] produce values for all models - TM
- [x] implement changes in the ETL - MM
- [x] implement graphic element on web portal in dev and prod - MR

**Comment by zperova** [comment]
first pass for MI-compliance score and how to calculate it here: https://docs.google.com/spreadsheets/d/1MD_83W_VRjwpx8pYINoGYsifQCk9FyNH7vNKB5xc_X8/edit#gid=2090308749

**Comment by Mandloi2309** [comment]
@zperova scores made available here: 
https://docs.google.com/spreadsheets/d/1MD_83W_VRjwpx8pYINoGYsifQCk9FyNH7vNKB5xc_X8/edit#gid=697949553

**Comment by mriios** [comment]
@zperova meter has been added to the FE

**Comment by mauroz77** [comment]
@zperova done
