### ISSUE TITLE
Licence info visible on the website

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1053]
### Description

As a user, I want to see the licence info on cancermodels.org

All models submitted before this implementation takes place should be marked as EBI Terms of use: https://www.cancermodels.org/about/terms-of-use

All models submitted after: https://creativecommons.org/publicdomain/zero/1.0/

### Acceptance criteria

- [ ] best implementation discussed within the relevant team members
- [ ] deployed

**Comment by zperova** [comment]
As discussed this change will be at the level of the model. A footer "All models and data in Cancer Models Finder are available either through CC0(link) or EMBL-EBI Terms of Use (link to https://www.ebi.ac.uk/about/terms-of-use)"

**Comment by zperova** [comment]
Example from GWAS:
General statement - https://www.ebi.ac.uk/gwas/downloads/summary-statistics
Individual study - https://www.ebi.ac.uk/gwas/studies/GCST90134433

**Comment by Mandloi2309** [comment]
License field added to sharing sheet (as decided it needs to be on model level). changes on dev

**Comment by zperova** [comment]
@Mandloi2309 does this mean that now this is now ready to move to the next step - and who is responsible for it? Many thanks!

**Comment by mriios** [comment]
Licence info has been added to the FE, both for model detail page and footer across all the site.
