### ISSUE TITLE
Link to raw data leads to nothing

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1058]
**Describe the bug**
The EGA link to raw data for SIDM01303 model doesn't link to the data.

**To Reproduce**
1. Go to https://www.cancermodels.org/data/models/CMP/SIDM01303
2. Click on any link in Raw data column
3. See empty page: https://ega-archive.org/search/site/EGAS00001002222

**Expected behavior**
Expect to see relevant data in EGA

**Screenshots**

![Screenshot 2023-01-25 at 12.51.27.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/8e70e8bb-8fc8-4947-879b-8f3b3c3b72df)
**Additional context**
It could be that other models have the same bug - didn't check others.

**Comment by Mandloi2309** [comment]
We need to update the raw data url link generation
