### ISSUE TITLE
[Data issue] Unify Tumour type value for provider inputs: (Metastasis, Metastatic)

### ISSUE THREAD

**Issue by ficolo** [PDXFinder/pdxfinder#1066]
As an user I would like to see a standard unified value for Tumour type = (Metastasis, Metastatic)

![Screenshot 2023-02-02 at 14.49.01.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/cc531e22-9a0a-4c4e-b478-82c89d03af8e)

Apparently the issue is with CMP models that have a value of Metastasis in tumour type, the rest of the providers have a value of Metastatic.

**Comment by mauroz77** [comment]
@zperova done
