### ISSUE TITLE
View Data link enabled for mutation data but table is empty

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#1067]
https://www.cancermodels.org/data/models/JAX/TM00025

![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/a8940d70-de2c-4107-845c-157024db75b2)

![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/906b0102-cbba-4b78-b142-90785cb50ccc)

**Comment by mauroz77** [comment]
@mriios @ficolo 
This seems to be a UI issue. I don't remember if known or not. The endpoint `https://www.cancermodels.org/api/details_molecular_data?or=(patient_model_id.eq.51539607556,xenograft_model_id.eq.51539607556,cell_model_id.eq.51539607556) ` retrieves correctly the flag for this record, informing that data_availability is false, and that's what is happening in the data: JAX_molecular_metadata-sample contains an entry for `BL0470F1820P0` with platform `mutation_Truseq_JAX` but there is no mutation data associated to that sample/platform. The UI should somehow inform about this instead of showing the VIEW DATA link which leads to an empty table when clicked.
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/17280f27-6e56-4e4b-aecb-c2d64f2b78c2)

**Comment by zperova** [comment]
@mriios @ficolo ?

**Comment by mauroz77** [comment]
@zperova done
