### ISSUE TITLE
Include "Precancerous" to Tumour type 

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1069]
### Description

As a user, I want to be able to search for models made from benign tumours. 

CMP has pre-malignant tumour models that we need to capture.

### Acceptance criteria

- [x] template update
- [x] update to Validator
- [x] ETL rerun 
- [x] front-end changes to add this as filter

**Comment by Mandloi2309** [comment]
Needs mapping for CMP models

**Comment by Mandloi2309** [comment]
Pre cancerous models are categorised as pre-malignant. We can already see the filter on the portal and the CMP models will require mappings @zperova
