### ISSUE TITLE
Display links to external resources for molecular data tables

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#1071]
### Description

As a developer, I want to have the equivalent functionality pdx-gun and the previous pdx-finder offered in terms of referencing external resources. This means displaying links pointing to external databases with additional information.

Example from pdx-finder:
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/f17cb8c3-d84f-4794-a9f2-0c539812c56f)

This ticket focuses on displaying links for columns in the molecular data tables:

- cna data: `HGNC Symbol`.
- mutation data: `HGNC Symbol` and `Amino Acid Change`.
- expression data: `HGNC Symbol`.
- cytogenetics data: `HGNC Symbol`.

### API details
The ETL now creates a new column called `external_db_links` which contains a JSON object with the data needed to create the links. The column is available in the current endpoints that are used to retrieve the molecular data:

- api/mutation_data_table
- api/cytogenetics_data_table
- api/expression_data_table
- api/cna_data_table

The structure of the `external_db_links` column is as follows:
```json
[
   {
      "column":"hgnc_symbol",
      "resource":"OncoMx",
      "link":"https://oncomx.org/searchview/?gene=TTLL11"
   },
   {
      "column":"amino_acid_change",
      "resource":"Civic",
      "link":"https://civicdb.org/links?idtype=variant&id=531"
   }
]
```
This should be interpreted by the UI as:

- Create a link in the column hgnc_symbol, with the url: https://oncomx.org/searchview/?gene=TTLL11, text: "OncoMx"
- Create a link in the column amino_acid_change, with the url: https://civicdb.org/links?idtype=variant&id=531, text: "Civic"

### Acceptance criteria

- [ ] Links displayed

**Comment by mauroz77** [comment]
@mriios @zperova this is the ticket to implement the corresponding changes in the UI. The endpoints are available in the dev database only.

**Comment by mriios** [comment]
Also need to remove that extra column from `.csv` download, at [src/apis/Details.api.ts:257](https://github.com/PDCMFinder/pdcm-web-ui/blob/1d47fcdc7effb70c78eae88653b6efc7c34bb0b2/src/apis/Details.api.ts#L256): `delete item.external_db_links;`
