### ISSUE TITLE
Change data type to from TEXT to NUMBER in molecular data table columns which are numeric

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#1074]
In order to be able to sort data correctly, we need to store numeric values as NUMBER type in the database. For now, this change is to be done in molecular data tables.

The change is in 2 levels: data (nulls to zero when it makes sense) and the actual change in the database.

## cna_molecular_data
- log10r_cna
- log2r_cna

## expression_molecular_data
- z_score
- rnaseq_coverage (?) no data so not sure what datatype
- rnaseq_fpkm
- rnaseq_tpm
- rnaseq_count
- affy_hgea_expression_value
- illumina_hgea_expression_value

## mutation_measurement_data
- read_depth
- allele_frequency
- seq_start_position

**Comment by zperova** [comment]
@mauroz77 How soon/urgent this needs to be done - in the context of current work priorities?

**Comment by mauroz77** [comment]
@zperova I think this is not urgent

**Comment by zperova** [comment]
allele_frequency
seq_start_position
rnaseq_coverage (?) no data so not sure what datatype

these fields can not be set to zero - need to explore alternative solutions

**Comment by Mandloi2309** [comment]
cna and expression data cleaned. Mutation left untouched
