### ISSUE TITLE
Support filtering for different types of treatment received

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1095]
### Description

As a user, I want to filter models on a specific type of treatment the patient received.

Treatment types:
- surgery
- radiotherapy
- chemotherapy
- immunotherapy
- targeted therapy (any drug and drug combination)
- hormone therapy

The grouping used are from here: https://www.cancer.org/cancer/managing-cancer/treatment-types.html

Document: https://docs.google.com/document/d/1cE2mB7HOtPi6z71zgjpa76IILE97-7BaqP6-P0LQxyE/edit#heading=h.rvypttmfeh3g 

### Acceptance criteria

- [x] data model changes in place
- [x] data updated in spreadsheets
- [x] templates updated
- [x] UI elements designed
- [x] Description of definitions included in the metadata dictionary
- [x] Models by patient-treatment visualisation added in the Data Overview 
- [x] implemented in production

**Comment by Mandloi2309** [comment]
in progress doc: https://docs.google.com/document/d/1cE2mB7HOtPi6z71zgjpa76IILE97-7BaqP6-P0LQxyE/edit
