### ISSUE TITLE
Metadata and data loading checks documentation

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#174]
### Description:

As a developer, I want to have documentation for metadata and data loading check to ensure correct loading
Jira ticket [PDXI-832](https://www.ebi.ac.uk/panda/jira/browse/PDXI-832?workflowName=jira&stepId=1)

### Acceptance criteria:

- [ ] documentation agreed on and available on GDrive

**Comment by zperova** [comment]
to collectively define that the dataset loaded correctly

**Comment by zperova** [comment]
@Afollet @CsabaHalmagyi this sounds like validation checks to me? would you consider this a duplicate of https://github.com/PDXFinder/pdxfinder/issues/284?

**Comment by Afollet** [comment]
No, this is for a document that guides an individual to the procedures of loading data. Like which steps a person should take to consider a data set successfully validated and loaded into the PdxFinder. The other document is for validation rules for the validation service. One document is for the human processes the other is for machine processes, IMO

**Comment by zperova** [comment]
I see, thanks @Afollet

**Comment by zperova** [comment]
this is now obsolete. closing
