### ISSUE TITLE
Ability to create data snapshots

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#183]
### Description:

As a EuroPDX member, I would like to have a PDX Finder snapshot to see what data is in the database.
Jira ticket [PDXI-844](https://www.ebi.ac.uk/panda/jira/browse/PDXI-844?workflowName=jira&stepId=3)

### Acceptance criteria:

- [x] snapshot with original diagnosis created
- [x] snapshot with harmonised diagnosis created

**Comment by Afollet** [comment]
This ticket was completed with #182
