### ISSUE TITLE
Retire PDXNet custom loaders

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#184]
### Description:

As a developer, i want to use the universal loader to ensure data loading via templates only.

XDog should be ran on all of the PDX Net data sets. Then each of these exports need to be validated and ran in the Updog to ensure that no data is being loss from the XDog. Additionally, the PDX Net data sets are very sparse and it needs to be ensured that the Updog with run the data sets without throwing runtime exceptions.

Yomi made the very excellent PDX-Transformer that will export both PDMR and JAX data sets which are on feeds. The PDMR exporter needs to be cleaned up and validated before using it. The Jackson Lab is in development of their own JAX to PDX Finder pipeline so it is unclear if it is necessary to spend any time cleaning the PDX Finder in-house tool.

Relevant ticket for PDMR: #296

Jira ticket [PDXI-864](https://www.ebi.ac.uk/panda/jira/browse/PDXI-864?workflowName=jira&stepId=1)

### Acceptance criteria:

Data sets exported and first pass cleaned:
- [x] PDXNet-HCI-BCM
- [x] PDXNet-WUSTL
- [x] PDXNet-Wistar-MDAnderson-Penn
- [x] PDXNet-MDAnderson 

Updog validator errors are investigation and fixed where appropriate
- [x] PDXNet-HCI-BCM
- [x] PDXNet-WUSTL
- [x] PDXNet-Wistar-MDAnderson-Penn
- [x] PDXNet-MDAnderson 

- [x] word press pages are linked if available

- [x] Custom Loader code is retired on Dev

**Comment by zperova** [comment]
this will require some clean-up

**Comment by zperova** [comment]
execute after release

**Comment by zperova** [comment]
split into separate tickets

**Comment by Afollet** [comment]
Export of HCI-BCM is blocked by #343

**Comment by Afollet** [comment]
@zperova Done

**Comment by zperova** [comment]
Great work, @Afollet Thank you!
