### ISSUE TITLE
Validate and load data Curie LC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#186]
### Description:

Validate and load data Curie LC
Jira ticket [PDXI-778](https://www.ebi.ac.uk/panda/jira/browse/PDXI-778)

validate and report - please load when validated- create a new ticket as required. Please note old data and new data have been merged into single spreadsheet to facilitate process

Metadata 
https://drive.google.com/drive/folders/1JG0xmXEze5MKvOuhR75njqN_LJaOpD0t

Mutation
https://docs.google.com/spreadsheets/d/15cDx9ROWWTSmUsmKeUcILL1u8SNA4tjAh17zjUsq7wo/edit#gid=0

CNA
https://drive.google.com/drive/folders/1JG0xmXEze5MKvOuhR75njqN_LJaOpD0t
Cytogenetics
https://docs.google.com/spreadsheets/d/1CqJ9JpFLlTnWoORL1g5PNw8x-oA4ZI4LpAQKux6747c/edit#gid=0

Drug dosing
https://docs.google.com/spreadsheets/d/1o-87o6x8f0DoA3PUz3oqa4Acs2nl8iVFlnI8iAhij_Y/edit#gid=0

Sample metadata
https://docs.google.com/spreadsheets/d/1qu-HMVHd8NMG2wPe-b4AaTQWTF4vI8LPME1yp01P6n0/edit#gid=0

Issues:
Drug dosing response is in percentage and not in the harmonized: Complete response, partial response etc.
What metrics can I use to convert this?

### Acceptance criteria:

- [x] metadata uploaded and validated
- [x] Mutation uploaded and validated
- [x] CNA uploaded and validated
- [x] Drug dosing uploaded and validated
- [x] Cytogenetics uploaded and validated
- [x] Sample metadata uploaded and validated

**Comment by zperova** [comment]
Comment from [Jira-892](https://www.ebi.ac.uk/panda/jira/browse/PDXI-892): update one model - which one?

**Comment by zperova** [comment]
we have metadata nad sample platform in the repo.
only loaded can and mut patient data
need to load drug dosin

**Comment by zperova** [comment]
RECIST:

complete response CR - all lesions disappear
partial response PR - a decrease of at least 30%
stable disease SD - no significant decrease or increase
Progressive disease PD  - an increase of at least 20%

TGI
45% PR
0%  SD
29% SD
71% PR
62% PR
29% SD
29% SD
4% SD
27% SD
66% PR
78% PR
18% SD
10% SD

**Comment by zperova** [comment]
Protocol for analysis in Drug dosing is missing (essential field)

**Comment by zperova** [comment]
As discussed - protocol for analysis in Drug dosing is not used at the moment. 
Data ready to load

**Comment by CsabaHalmagyi** [comment]
Additional cleanup done:

Patient sheet:
Typo in patient id: HLCF-25 this should be 15, everywhere else in the template LCF15 is referred.
Model sheet:
Missing passages for LCF15. Used the passage definitions from the validations sheet.
Validation sheet:
For model LCF11 passage value 2-1 was renamed to 2,1

With the mentioned changes the metadata loaded fine.

No new diagnosis combinations in the new models, so no need to definie additional mapping rules by @zperova

**Comment by CsabaHalmagyi** [comment]
CNA and Mutation data uploaded. @Afollet to run pipeline on the mutation, since we have two different genome_assembly.

**Comment by Afollet** [comment]
The mutation data contains "0" in the Alt column in five rows. These do not pass QC on the annotation pipeline.

[https://app.zenhub.com/files/78657127/85fc0e4f-a57a-4062-8c63-1923a6a98095/download](https://app.zenhub.com/files/78657127/85fc0e4f-a57a-4062-8c63-1923a6a98095/download)

@CsabaHalmagyi 
This may be worth briefly mentioning with the provider if you do not know the origins of these bugs.

**Comment by zperova** [comment]
done. Next step: https://github.com/PDXFinder/pdxfinder/issues/308
