### ISSUE TITLE
JAX omics data loading in template format

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#190]
### Description:

As a developer, I want all the PDX models data to be loaded in standard manner to ensure consistency.

### Acceptance criteria:

- [x] JAX omics data is loaded according to PDXFinder template

**Comment by zperova** [comment]
@sneuhaus since we are using Github to track issues, I assigned you to this one, even though you are not working in our sprints.

**Comment by sneuhaus** [comment]
The metadata templates and mutation data are now available in the the formats
http://tumor.informatics.jax.org/PDXInfo/
