### ISSUE TITLE
Load expression fastqs from PDMR to ENA

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#193]
### Description:

Expression data fastqs from PDMR need to be loaded to ENA to avoid them sitting on the cluster.

### Acceptance criteria:

- [ ]  expression data fastqs from PDMR are submitted to ENA
- [ ] links to ENA provided on the PDXFinder for relevant models

**Comment by Afollet** [comment]
Spent a sprint organizing RNASeq data to re-submit including:

*Submitting samples that were not included in WES
*Refactoring bespoke data pipeline for readability
*Investigating failure of MD5Checksums and debugging scripts/FTP clients

As of Aug13 I am:

*Downloading a missing set of 800 FASTQS from NCI server. Problems with connection sometimes happen and the processes needed to be checked in on. 
*Once downloaded I can uploaded what is needed to the ENA. Then I should be able to complete the submission.

*Once submission is complete I will need to troubleshoot md5sum errors for RNASeq.
*Problems with md5 sums persist for WES. Switched to using ASPERA. I am waiting to see if more md5sums come back as failures before resbsubmitting
