### ISSUE TITLE
Upgrade software

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#199]
### Description:

As a PDXFinder developer, I want to upgrade the software to ensure proper work of the resource.

Jira [PDXI-642](https://www.ebi.ac.uk/panda/jira/browse/PDXI-642?workflowName=jira&stepId=4)

### Acceptance criteria:

- [x] upgraded to Spring 2.0
- [x] tests finished

**Comment by zperova** [comment]
More complex issue than anticipated

**Comment by zperova** [comment]
tests will be finished by the end of today

**Comment by zperova** [comment]
@sprintell to review pull request once ready by EOW

**Comment by CsabaHalmagyi** [comment]
This is done now.
