### ISSUE TITLE
One model not marked as EurOPDX project

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#204]
### Description

One model is missing from EurOPDX project.
![Screenshot 2020-07-23 at 21 07 18](https://user-images.githubusercontent.com/38244059/88334063-194c3780-cd29-11ea-9d32-4fee106162a2.png)
![Screenshot 2020-07-23 at 21 07 35](https://user-images.githubusercontent.com/38244059/88334088-1e10eb80-cd29-11ea-81c1-24660eae7ac8.png)

### Acceptance criteria
- [x] missing model added to the EurOPDX project

**Comment by zperova** [comment]
This is fixed locally, @CsabaHalmagyi will pushed once gitlab is back on

**Comment by CsabaHalmagyi** [comment]
VHIO_PC-PDX-108.2	has been added to EuroPDX project.
