### ISSUE TITLE
Investigate problems with pdxfinder-lfs repository

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#205]
### Description

Pointers in the pdxfinder-lfs repo files can not be resolved
Repo can not be cloned 

### Acceptance criteria

- [x] plan for solution for how to enable git-lfs to work in place

**Comment by zperova** [comment]
A meeting scheduled with @rmwthorne on Friday August 6

**Comment by rmwthorne** [comment]
Summary of meeting: 
Previous support tickets: [397235](https://helpdesk.ebi.ac.uk/SelfService/Display.html?id=397235), [430455](https://helpdesk.ebi.ac.uk/SelfService/Display.html?id=430455).
From communication with web prod team, new storage is being procured for git-lfs object store, specifically for replication in case of failover. Ongoing status is reported in ticket [437034](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=437034).

For now we have agreed to reverse git-lfs tracking of the main data repository and continue to use that with the increased limits, and use the git-lfs version when the storage becomes available.
