### ISSUE TITLE
Load CHOP data PPTC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#207]
### Description

Data load for PPTC - 261 PDX models from 37 unique pediatric cancers: https://drive.google.com/drive/folders/1ffbMtp6YeLyAYlxi1Rnc-_gUKlb2DrxP

Publication: https://pubmed.ncbi.nlm.nih.gov/31693904/
Data on Figshare: https://figshare.com/projects/Genomic_landscape_of_childhood_cancer_patient-derived_xenograft_models/38147
Data on pedcBioportal: 	https://pedcbioportal.org/login.jsp#summary
Communication in email

### Acceptance criteria

- [x] metadata received and validated
- [x] data received
- [x] data validated and harmonized
- [x] metadata loaded
- [x] data loaded

**Comment by zperova** [comment]
@zperova to confirm the following attributes are correct in the metadata template:
- data source abbreviation
- primary tissue
- diagnosis
- tumor type

**Comment by Afollet** [comment]
I have documented some of the issues with the metadata workbook. Some of these can be resolved brief discussions with colleagues: 

NA exists on Age at Initial Diagnosis -- was this Not collected or Not provided

There are very young patients with fractional years .17, .25, .33, .5 
Are columns in NA not provided or not collected?

In sample sheet

	NA's cannot exits in Sample ID. Although, we can generate one if neccessary. However, if data 		exist for this sample in the associated metadata it can only be linked if the Sample Id's are 		matching.

	Relapse events must be resolved into time time elapsed between events.

	"post-treament" and not specified exists in tumour_type

	stages exists without a staging system?

	age_in_years_at_collection is empty.

	Unknown is mapped to 'Not Collected' correct? Is Not collected supported by the PDX Finder?


In model sheet:

	Contains the following host_strain/host_strain_full pairs:

	CB17-SCID	C.B-Igh-1b/IcrTac-Prkdcscid Taconic
	NOD/SCID (ABR)	NOD.Cg-Prkdcscid/J
	NOD/SCID and 3KO	NOD.Cg-Prkdcscid/J
	NOD/SCID and NSG (ABR)	NOD.Cg-Prkdcscid/J
	NOD/SCID and NSG	NOD.Cg-Prkdcscid/J
	NOD/SCID	C.B-17IcrHanHsdArc-Prkdcscid
	NOD/SCID	NOD.Cg-Prkdcscid/J
	NSG (ABR)	NOD.Cg-Prkdcscid/J
	NSG (ABR)	NOD.Cg-Prkdcscid Il2rgtm1Wjl/SzJ
	NSG	NOD.Cg-Prkdcscid/J
	NSG	NOD.Cg-Prkdcscid Il2rgtm1Wjl/SzJ
	Rag1 KO	NOD.129S7(B6)-Rag1tm1Mom/J
	RAG2	NOD.Cg-Rag2tm1Fwa Tg(TcraTcrbNY8.3)1Pesa

	Why is their equivalent host strain nomenclature with unequivalent host_strain:

	NOD/SCID and 3KO	NOD.Cg-Prkdcscid/J
	NOD/SCID and NSG (ABR)	NOD.Cg-Prkdcscid/J
	NOD/SCID and NSG	NOD.Cg-Prkdcscid/J
	NOD/SCID	NOD.Cg-Prkdcscid/J
	NSG (ABR)	NOD.Cg-Prkdcscid/J
	NSG	NOD.Cg-Prkdcscid/J

	Also, why are their "and" statements?

	Sample state is not filled. 

model_validation - passages_tested is filled with "Not specified" 

Sharing --
	provider_type, accessibility, and europdx_acess_modality

	Shouldn't project be "EuroPDX" ?

**Comment by Afollet** [comment]
@zperova cbioportal dump is on the gDrive. No need to request it.

**Comment by zperova** [comment]
> @zperova cbioportal dump is on the gDrive. No need to request it.

@Afollet thanks for checking this!

**Comment by zperova** [comment]
Please correct to "Not specified" everywhere where the input value is not an allowed one (there is no more metadata we can get from the provider at this point) - i know there are several instances throughout the metadata template.

I will update on the strains later.

**Comment by Afollet** [comment]
@zperova We want to load both the CNA and MUT data for this metadata, correct? They in the gDoc in atleast cbioportal format. However, this may take me sometime to do. Therefore, I want to confirm this.

**Comment by zperova** [comment]
@Afollet yes we would like to load all the data available. Please adjust the estimate as needed if this requires extra work.

**Comment by Afollet** [comment]
Inferred mappings:
What they gave us / What is in the CBioPortal data / explanation 

Patient ID / Patient ID / Both these match

(patient) Sample ID / Matched_Norm_Sample_Barcode /  If they provided us the normal sample instead of the tumor sample from the patient the metadata column "sample_id" is  incorrect. This, however may be arbitrary since the patient Sample ID's may not be referenced in the molecular data and not used in the data set.

Model Id / Tumor_Sample_Barcode / These are matching. I would assume Tumor_Sample_Barcode is a patient Sample ID because of the existence of the column "Matched_Norm_Sample_Barcode". Therefore, I am uncertain if these are tumors implanted in xenografts and then sequenced or just the matching patient tumor sample. However, the publication only clearly talks about working with genomic data from PDX models.


Further problem, between the PDX Finder data model of patient-sample-model data structure and the cbioportal data model of patient-sample.

From the description:

 Funding provided by <a href='https://www.alexslemonade.org/'>Alex's Lemonade Stand Foundation</a>, enabled us to <a href='https://www.biorxiv.org/content/10.1101/566455v2'>genomically characterize</a> a major subset of 261 PDX models. We used WES, RNA-Seq, and SNP arrays to characterize the PDX models.

I am going to carry on transforming the data they have available assuming that there is only passage 0 of every xenograft model and that per model there is only one xenograft sample.

**Comment by zperova** [comment]
@Afollet there is only one passage of every model (passage 0), however, there are multiple models form the same patient
Another thing I noticed - correct pubmed ID is this one for all the models - PMID: 31693904 - there is a formatting bug.

**Comment by zperova** [comment]
I am not yet familiar with the cbioportal data model, need to look it up

**Comment by Afollet** [comment]
@zperova The correct PMID is 31693904 for all of them. I see that Excel incremented the PMID for every cell.

A patient can have many models. That is correct logic and happens frequently. I'm not sure if there is any sort of bug there.

Here is the cbioportal file formats https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#clinical-data

I believe the clincal sample files and their metadata carry the most sample/model information.

**Comment by zperova** [comment]
thanks @Afollet

**Comment by Afollet** [comment]
Complete a basic export of expression,cna, and mutation data from the cbioportal file formatted data. I placed in the 'data_quarantine' folder in the git repository. These files, cna, mut, and expression, will need all the sample/model information filled by using a completed 'sampleplatform.xlsx' sheet. As well as the genome assembly and platform information.

I am now blocked by waiting for correspondence from the provider.

We do not have a provider page for PPTC or platform pages for any of this data. We will need to contact the provider ask for the content necessary for these.

**Comment by zperova** [comment]
waiting for the provider. moving on to the next sprint.

**Comment by zperova** [comment]
waiting for the provider. moving on to the next sprint. @zperova email provider and remind about the deadline for this release

**Comment by zperova** [comment]
provider waiting to collate data from others involved. Data will not make this release, upload metadata only

**Comment by Afollet** [comment]
I'm revisiting this data set to see what additional information we need to load the molecular data

**Comment by zperova** [comment]
👍

**Comment by Afollet** [comment]
Molecular variant data is being test on the UPDOG is complete. This data set will now only require correspondence with our contact.

The last two remaining tasks:

- Resolve all the metadata.xlsx issues I brought up with our contact
- Platform pages do no exists for CNA, MUT, and Expression. I have yet to ask for these.

**Comment by zperova** [comment]
closing this one. Will make a separate for remaining tasks
