### ISSUE TITLE
Load additional models for DFCI

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#208]
### Description

Load additional 40+ models to DFCI data.

### Acceptance criteria

- [x] metadata template validated
- [x] data validated and harmonized
- [x] data loaded

**Comment by zperova** [comment]
Provider contacted, currently on break. Will check next week again as no dates given.

**Comment by zperova** [comment]
Template received 6 May 2021

**Comment by zperova** [comment]
Received template here: https://docs.google.com/spreadsheets/d/18aTRtwpv1mp8YeqphCocO-B557vipir8/edit?usp=drive_web&ouid=110548651158605123831&rtpof=true

**Comment by Afollet** [comment]
Done
