### ISSUE TITLE
Create WP pages for Curie-LC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#234]
### Description:

As a provider, I want to see Drug dosing platform description for Curie-LC

Example for the format: http://www.pdxfinder.org/platform/jax-drug-dosing/

Jira ticket [PDXI-777](https://www.ebi.ac.uk/panda/jira/browse/PDXI-777)

### Acceptance criteria:

- [x] Curie drug dosing platform page created and has correct info
- [x] Platform page links correctly

**Comment by zperova** [comment]
Drug dosing WP info: https://drive.google.com/drive/folders/1u4rbEUzKVez2hjhohbvtGt571LazzzlG

**Comment by CsabaHalmagyi** [comment]
Created the page and updated the data with the url

**Comment by zperova** [comment]
👍

**Comment by zperova** [comment]
done
