### ISSUE TITLE
Upgrade Spring to 2.3.1

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#235]
### Description:

As a PDXFinder developer, I want to upgrade the software to ensure proper work of the resource.

### Acceptance criteria:

- [x] upgraded to Spring 2.3.1
- [x] tests done

**Comment by zperova** [comment]
@CsabaHalmagyi and @jmason-ebi to spend 2 hours working on this - if harder than anticipated, drop for this sprint

**Comment by CsabaHalmagyi** [comment]
On Friday Jeremy and I were looking into this but couldn't finish the upgrade due to versioning issues with the neo4j ogm.

**Comment by CsabaHalmagyi** [comment]
Upgraded Spring to 2.3.3

**Comment by CsabaHalmagyi** [comment]
After many many hours of desperate googling, code fixing and dependency resolving, I am happy to say that upgrading spring boot is done.

**Comment by zperova** [comment]
👍 Thanks @CsabaHalmagyi
