### ISSUE TITLE
Create mappings for CHOP data PPTC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#249]
### Description:

Jira ticket [PDXI-733](https://www.ebi.ac.uk/panda/jira/browse/PDXI-733)

Create mappings: 

please continue making mappings for the CNA, Transcriptomic, and Fusions templates if needed. Mutations mapping is done.
[Mutation](https://docs.google.com/spreadsheets/d/1FuSWLWTa90iE5X9hxGjV0wgDE4FF2sC5P-4krX3Qqf4/edit#gid=0)MAPPING FILE
TBD:
Fusion, copy number alteration, transcriptomic
Sample metadata file.

useful info:
minutes from the Maris's lab collection https://docs.google.com/document/d/1mJeEBflXnUVEfGwwYJHsw_KkyPIZrXkWpe94XUd-hCw/edit#

useful links :
Paper: https://www.biorxiv.org/content/10.1101/566455v2.full

Data: https://pedcbioportal.org/study/summary?id=pptc - Jo Lynne : What is on pedcbio is essentially what we have for this dataset. I also uploaded files to [FigShare](https://figshare.com/projects/Genomic_profiling_of_childhood_tumor_patient-derived_xenograft_models_to_enable_rational_clinical_trial_design/38147) and am attaching the [final table S1](https://drive.google.com/file/d/1fP18iPFskTTOUvrJViQ4_eLNz1MOoZXu/view).

### Acceptance criteria:

- [x] mappings are created

**Comment by Afollet** [comment]
This ticket was the task to be completed prior to the data load. I would consider it done.

**Comment by zperova** [comment]
closing.
