### ISSUE TITLE
Store raw data link on molecular characterization

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#253]
### Description:

Steps:
1. add placeholder on molecular characterization node
2. alter the domain object creator to store raw data link on MC.

Jira ticket [PDXI-833](https://www.ebi.ac.uk/panda/jira/browse/PDXI-833)

### Acceptance criteria:

- [x] done

**Comment by Afollet** [comment]
This needs to be reviewed for completion. I believe it is done.
