### ISSUE TITLE
Update IRCC-CRC CNA data with Gene Symbols

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#255]
### Description:

As a user, I want to see gene symbols in the CNA data.

Jira ticket [PDXI-893](https://www.ebi.ac.uk/panda/jira/browse/PDXI-893)

### Acceptance criteria:

- [ ] IRCC-CRC CNA data updated with gene symbols

**Comment by Afollet** [comment]
IRCC-CRC CNA data already contains gene symbols. I believe this ticket is refering to UOC-BC cna data that is currently in '/data-quarantine' and does not contain gene symbols.

**Comment by Afollet** [comment]
Closing
