### ISSUE TITLE
Load PMLB colon data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#266]
### Description 

Get the Princess Margaret Living Bank data following up Nhu-An Pham email
3 more cohorts (colon, lung and pancreas) - to be sent end of August

### Acceptance criteria

- [x] transform data 
- [x] colon data is in GitLab repo
- [x] colon metadata and data validated and loaded

**Comment by zperova** [comment]
Email sent

**Comment by Afollet** [comment]
I have recieved the Lung cohort metadata. I am confirming with Nhu-an that this data is ready for release mid-September. The associated mut and cna data is on the cbioportal.ca and needs to be extracted using the cbioportal json

**Comment by Afollet** [comment]
Lung cohort is not ready for release. However, just received the pancreas cohort that can be released in the next data set.

**Comment by zperova** [comment]
Well done and great news @Afollet ! a very productive week 👍

**Comment by Afollet** [comment]
Placed metadata in git repo "data_quarantine".  Transferred to updated template. All models with POP will need to be prepended with "PMLB_" as requested. There is an unamed model that will need to be resolved. This data is going to be concatonated with the existing PMLB data.

There is molecular characterizations for this data on cbioportal.ca. I have contacted the developer at PMLB to request permission be granted to my user to retrieve these from the Swagger API. They will then need to be parsed using the cbioportal JSON parsing pipeline in the PDX Finder app.

I have request the sampleplatform.xlsx sheet associated with this data set and the information needed for the Word press pages.

**Comment by Afollet** [comment]
Loaded the Colon data into the repo

**Comment by zperova** [comment]
close this one, create a separate ticket for pancreas and lung data @zperova

**Comment by Afollet** [comment]
Waiting for Sample Platform, correspondence for cbioportal, and documents for word press pages.

**Comment by zperova** [comment]
> close this one, create a separate ticket for pancreas and lung data @zperova

this comment should be ignored, as ended up modifying the ticket.

**Comment by Afollet** [comment]
Recieved and added sampleplatform data to the repo for the Colon dataset

**Comment by Afollet** [comment]
There are additional mappings needed here @zperova

**Comment by Afollet** [comment]
I have been granted access to the data sets and will export them to templates. The wordpress page is here: http://dev.pdxfinder.org/platform/pmlb-crc/

**Comment by Afollet** [comment]
For the task of parsing the data a new ticket has been made #322

**Comment by zperova** [comment]
@Afollet I believe we need to remove the first sentence from the Wordpress pages for better reading experience. Also I am not sure the title is the best fit for this type of page.

**Comment by zperova** [comment]
updated page looks very nice, thank you @Afollet

**Comment by Afollet** [comment]
@zperova This ticket is done.

I would like to have one last review of all the data I loaded before the release.

**Comment by zperova** [comment]
great, thanks @Afollet
