### ISSUE TITLE
Dependencies cannot be resolved on dev

### ISSUE THREAD

**Issue by CsabaHalmagyi** [PDXFinder/pdxfinder#268]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dependencies ....................................... FAILURE [  0.509 s]
[INFO] parent ............................................. SKIPPED
[INFO] data-model ......................................... SKIPPED
[INFO] data-services ...................................... SKIPPED
[INFO] indexer ............................................ SKIPPED
[INFO] web ................................................ SKIPPED
[INFO] admin .............................................. SKIPPED
[INFO] pdx-finder 1.0.0 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.782 s
[INFO] Finished at: 2020-08-10T04:22:08+01:00
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.8.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.4: Could not transfer artifact org.jacoco:jacoco-maven-plugin:pom:0.8.4 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.8.4/jacoco-maven-plugin-0.8.4.pom. Return code is: 501, ReasonPhrase:Not Implemented. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by CsabaHalmagyi** [comment]
Upgrading the maven version to 3.6  in jenkins seems to solve this problem.

**Comment by zperova** [comment]
done
