### ISSUE TITLE
Set up Central Maven repo for pdx data core

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#275]
### Description

As a developer, I want PDXFinder to be a toolkit of microservices.

Necessary details here: [Jira-480](https://www.ebi.ac.uk/panda/jira/browse/PDXI-480)

### Acceptance criteria

- [x] account set up for OSSRH
- [x] PGP keys are generated and shareable to PDX Finder
- [x] Integration for publication is set up for the Data-Model
- [x] Data-Model is published

**Comment by Afollet** [comment]
I am reading the documentation here to understand the requirements of publishing: https://central.sonatype.org/pages/apache-maven.html

**Comment by Afollet** [comment]
Data-Models Repo https://github.com/PDXFinder/data-model

**Comment by Afollet** [comment]
I added your information to the POM (name and EBI email) as a developer @CsabaHalmagyi, as well as mine. FYI

**Comment by Afollet** [comment]
SNAPSHOT is on repo
<dependency>
  <groupId>org.pdxfinder</groupId>
  <artifactId>Data-Model</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>

**Comment by zperova** [comment]
carry over to the next sprint

**Comment by Afollet** [comment]
Appears to be published here: https://search.maven.org/artifact/org.pdxfinder/data-model/1.0.0/jar

I am going to test it with the rest of the PDX Finder app and push this change to Dev.

**Comment by Afollet** [comment]
added information in the wiki on this deployment pipeline: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/data-model+deployment

**Comment by zperova** [comment]
@CsabaHalmagyi to close once checked

**Comment by zperova** [comment]
done
