### ISSUE TITLE
Create WP pages for LIH data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#277]
### Description

As a user, I want to see details of how data has been collected for the LIH models.

Original Jira ticket [PDXI-847](https://www.ebi.ac.uk/panda/jira/browse/PDXI-847?workflowName=jira&stepId=3)

Protocols word press

**Please fuse platform and analysis documents- this will cover both CNA and Mutation so one WP protocol page will link both –
platform:
https://drive.google.com/file/d/1zeGEEck-qSKyhOpK8uA_0xUMGnmRRw1J/view?usp=sharing

Data analysis:
https://drive.google.com/file/d/1JoFQvc1XgznO0HtPYsZuNln4mJbr1xfp/view?usp=sharing

### Acceptance criteria:
- [x] Protocol WP pages are created
- [x] WP pages are linked

**Comment by zperova** [comment]
carryover

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Created pages:

CNA:
http://dev.pdxfinder.org/platform/lih-cna/

Mutation:
http://dev.pdxfinder.org/platform/lih-mutation/

Cyto (we do not have any information on Norlux IHC platform):
http://dev.pdxfinder.org/platform/lih-cyto/

**Comment by zperova** [comment]
thanks @CsabaHalmagyi I will make a separate ticket for the LIH IHC platform
