### ISSUE TITLE
Add link to Pubmed for associated publication

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#278]
### Description

As a user, I want to see a link to [Pubmed](https://pubmed.ncbi.nlm.nih.gov/) for the publication associated with the PDX model.

### Acceptance criteria

- [x] link to the relevant publication on Pubmed added

**Comment by zperova** [comment]
this is a software change

**Comment by mauroz77** [comment]
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/55438c41-8a2e-4c57-a971-a3d4367f373c)
@zina, @Afollet @CsabaHalmagyi This is how it looks in my local env. Any thoughts?

**Comment by zperova** [comment]
@mauroz77 This looks good to me. Thank you!

**Comment by mauroz77** [comment]
PR created: https://github.com/PDXFinder/pdxfinder/pull/519

**Comment by mauroz77** [comment]
@zperova done. See example: http://dev.pdxfinder.org/data/pdx/PPTC/IC-2305GBM

**Comment by zperova** [comment]
Great, thanks!
