### ISSUE TITLE
Add search by model ID

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#279]
### Description 

As a PDXfinder user, I want to search models by their ID.

### Acceptance criteria

- [ ] search by model id implemented

**Comment by CsabaHalmagyi** [comment]
This is done but putting it on hold until reviewing the solution provided by EuroPDX.

**Comment by zperova** [comment]
EurOPDX solution was sent via email. Closing.
Thank you @CsabaHalmagyi for implementing this!
