### ISSUE TITLE
Display official strain nomenclature

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#282]
### Description 

As a PDXfinder user, I want to easily find information about the strain used to generate PDX model.

The current view is of the non-official name which is not harmonized. 
![Screenshot 2020-08-13 at 16 02 44](https://user-images.githubusercontent.com/38244059/90151314-7f533a00-dd7e-11ea-8de0-b203206fbcb6.png)

### Acceptance criteria

- [x] official strain nomenclature is visible

**Comment by Afollet** [comment]
Query of dev db shows specimen number by Host Strain Nomenclature: 
source[https://app.zenhub.com/files/78657127/7d285104-766d-4b28-b927-39a19a99931e/download](https://app.zenhub.com/files/78657127/7d285104-766d-4b28-b927-39a19a99931e/download)
source2[https://app.zenhub.com/files/78657127/d424e7ee-c13d-4446-a2dc-c13d0df1a56f/download](https://app.zenhub.com/files/78657127/d424e7ee-c13d-4446-a2dc-c13d0df1a56f/download)

It is clear that the database needs cleaning

**Comment by Afollet** [comment]
I think another document should be prepared with some guide lines to names and host strain nomenclatures with accept names for common host strains and formatting for their nomenclatures. 

Here is a query of common name by symbol [https://app.zenhub.com/files/78657127/4510a6a4-e09b-4637-a30e-8e69cf6481c6/download](https://app.zenhub.com/files/78657127/4510a6a4-e09b-4637-a30e-8e69cf6481c6/download)

**Comment by mauroz77** [comment]
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/414d4f05-54b4-48c8-a8d2-39f491c8d094)
@zperova, @CsabaHalmagyi, @Afollet : I'm adding a tooltip when you hover over Host Strain Name. Any thoughts?

**Comment by Afollet** [comment]
I think that is a good approach.

There are these "Not Specified" Host Strain Names. For Example: http://dev.pdxfinder.org/data/pdx/crl/CRL-2835

I wonder if there is a way to gracefully handle this "Not Specified". Maybe in this exception the Host Strain Nomenclature can just be displayed in the cell? "Not Specified" is just distracting from useful information being displayed.

**Comment by zperova** [comment]
@mauroz77 This looks very nice! I think this is a much cleaner solution than having an additional column. Can it handle the formatting? in the provided example "Foxn1" should be Italics and "nu" superscript.

I agree with @Afollet about the Not specified cases. It's really sad to look at the models that have "Not specified" in almost every single field... Makes me think there is another data clean-up to be done - that can be aligned with the assignment of the "FAIR score" for the models.

**Comment by mauroz77** [comment]
@Afollet I could set the in the dto the value for the nomenclature if the host strain name is Not Specified. But, would the nomenclature be different to Not Specified as well? I was looking at my local data and one node with host strain name Not Specified has the nomenclature (symbol) with that value as well. I'm copying the prod database to my local machine to see if I can find other values.

@zperova we can put format to the tooltip but I think the value should be stored in the database with the corresponding html: <i>Foxn1</i>1<sup>nu</sup>. Otherwise the frontend would not have enough information to know how to format it

**Comment by Afollet** [comment]
@mauroz77 Host Strain Nomenclature is a hard requirement. The Host Strain Nomenclature should be more consistent than the Host Strain Name and is a hard requirement for the DB. If we have neither have values then it might as well say "Not Specified".  This should be a small minority of cases that we can only fix by contacting the data providers.

@zperova 
I agree with Mauricio. We would have to store the HTML tags or use some kind of vocabulary to resolve how to format this strings. Some of the Host Strain Nomenclatures have HTML tags in them currently, but this is something I've been trying to clean from the database.
