### ISSUE TITLE
Prepare technical test for upcoming job interviews

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#285]
### Description 

As a PDXfinder developer, I want to update existing technical test for the new interviews for a [software developer position](https://www.embl.de/jobs/searchjobs/index.php?ref=EBI01673) (job closing date 31 August 2020).  

### Acceptance criteria

- [ ] technical test updated

**Comment by CsabaHalmagyi** [comment]
Created test here:
https://www.hackerrank.com/work/tests/878870/questions

Sections:
Javascript/HTML/CSS - 10 questions
Java - 8 questions
Database - 1 question
Development - 1 question

**Comment by zperova** [comment]
needs to be published, not yet visible

**Comment by zperova** [comment]
to be shared via email

**Comment by CsabaHalmagyi** [comment]
Link: https://www.hackerrank.com/work/tests/878870/questions
Finalised the test and published it. I do not have the permission to invite anyone to complete this test.

Test duration: 60 mins

Sections:
JavaScript/HTML/CSS: 11 questions, 150 points
Java: 8 questions, 80 points
Database: 1 question, 50 point
REST: 2 questions, 20 points
Custom questions: 3 questions, 60 points

A correct answer in a multiselect question worths 10 points, an incorrect answer is -5 points.
The last 3 (freetext) questions should be evaluated manually after the test is completed by the candidate.

**Comment by zperova** [comment]
done. sent
