### ISSUE TITLE
Load VHIO-CRC data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#288]
### Description

As a PDXFinder developer, I want all the possible data supporting the models to be in the resource.

GDrive: https://drive.google.com/drive/folders/1F4Y8UJSkiyPtSiLKL5SBNNxzEsNnApAp

Jira ticket PDXI-791

### Acceptance criteria

- [x] communication with provider established https://github.com/pdxfinder/pdxfinder/issues/217
- [x] metadata validated and loaded
- [x] exome data loaded

**Comment by Afollet** [comment]
Exome data existing on the Gdoc loads with the exception of CTAX023 which does not exist in the metadata. I will need to contact the provider to resolve CTAX023. Until then I have removed that sample from the mut data in the UPDOG.

Metadata that is previously in UPDOG also loads correctly and the metadata is of high quality.

**Comment by Afollet** [comment]
I just recently emailed the contact informing them of the state of the data load and the additional documents that we would need to create their word press pages.

**Comment by Afollet** [comment]
Sample platform and information for wordpress page has been received.  I am adding a tick box to this ticket for the creation of a word press page.

**Comment by zperova** [comment]
Great work @Afollet !

**Comment by Afollet** [comment]
Done @zperova 

Starting new ticket for raw read submission for this set.

**Comment by zperova** [comment]
Great, thanks @Afollet
