### ISSUE TITLE
Load TRACE data - KU Leuven

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#291]
### Description

As a developer, I want to load all available PDX models and data from TRACE into the PDX Finder. 

GDrive: https://drive.google.com/drive/folders/16_lx6aiON6ajHyx-xtN6zo7YmLP1VMpO

### Acceptance criteria

- [x] metadata validated and loaded

**Comment by zperova** [comment]
Deadline for data given to provider: 18 September 2020
Waiting on the provider to send over templates and data

**Comment by zperova** [comment]
There is no data available for loading at this time - only metadata

**Comment by zperova** [comment]
@CsabaHalmagyi I believe the template is old and needs to be updated. Also, the metadata template states that patient treatment data is available but it is not at the moment as confirmed by the provider.

**Comment by CsabaHalmagyi** [comment]
Loaded metadata. Needed to harmonize the tumor types as they were using some not acceptable values.

**Comment by CsabaHalmagyi** [comment]
This is done now.

**Comment by zperova** [comment]
thanks @CsabaHalmagyi
