### ISSUE TITLE
Add RNASEQ accessions to PDMR sampleplatform

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#296]
As a user I would like the PDX Finder to be integrated with ENA accession.

Now that RNASEQ has been submitted to the ENA, the ENA accessions need to be placed in the PDMR sampleplatform so the links are generated on the PDX Finder front end.

**Comment by Afollet** [comment]
It appears the samples have yet to be re-released with the new RNASEQ Runs and Experiments. I will need to wait a few days and if they are not released then I will contact the ENA Help Deskt

**Comment by Afollet** [comment]
I received the .txt document with the accessions for my submitted RNASEQ files. However, I was never emailed confirmation and their are not trace of the records on the ENA. The ENA takes a while to crawl the submitted files, I believe this is why the incorrect checksums/blank files email trickle, so I'm going to leave this until I get back in week of Sept 22nd.

**Comment by zperova** [comment]
Paused for now

**Comment by zperova** [comment]
good to have in this release.

**Comment by Afollet** [comment]
Previous submission for RNASEQ experience some kind of internal error. I am awaiting response from the ENA to advise me on the best course of action.

**Comment by Afollet** [comment]
Resubmitted FASTQ's. Beginning to clean values in PDMR-Transformer. I will add a feature that adds the accessions automatically to the transformer so it will be automatically done in the future with each update to PDMR.

This is relevant to ticket for custom loader cleanups: #184

**Comment by Afollet** [comment]
This ticket is done. Carry on work with #184

@zperova

**Comment by zperova** [comment]
thanks @Afollet
