### ISSUE TITLE
VHIO-CRC exome word press page

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#300]
Platform description has been recieved from VHIO-CRC. We simply need to create the word press page and test that the platform URLS link appropriately on DEV.

[https://app.zenhub.com/files/78657127/d2d13073-731b-48a1-bd48-5ebac90644af/download](https://app.zenhub.com/files/78657127/d2d13073-731b-48a1-bd48-5ebac90644af/download)

### Acceptance criteria

- [x] word press page has been created 
- [x] URLS have been added to URL sample platform
- [x] platforms confirmed to link word press page on DEV

**Comment by Afollet** [comment]
[https://app.zenhub.com/files/78657127/61d330e3-3beb-4385-91ee-9d679292ac3d/download](https://app.zenhub.com/files/78657127/61d330e3-3beb-4385-91ee-9d679292ac3d/download)

**Comment by Afollet** [comment]
Word press page on Dev: http://dev.pdxfinder.org/platform/vhio-crc-wes/

**Comment by zperova** [comment]
word on DEV. done
