### ISSUE TITLE
Upgrade Neo4j server on ves-ebi-bc

### ISSUE THREAD

**Issue by CsabaHalmagyi** [PDXFinder/pdxfinder#301]
With the Spring boot upgrade we need to upgrade the neo4j server on the dev machine. 

- [x] Neo4j 3.5.21 installed on bc
- [x] Deployment jenkins scripts updated

**Comment by CsabaHalmagyi** [comment]
Installing new neo4j server is done on BC.

**Comment by CsabaHalmagyi** [comment]
Installation is done and deployment scripts have been changed for _DEV

**Comment by zperova** [comment]
done
