### ISSUE TITLE
Fix Details page - links do not open in dev

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#303]
Details pages do not open in dev.
Missing library.

**Comment by CsabaHalmagyi** [comment]
This was due to the following:

Foundation icons mime type were changed
Thymeleaf security change won't allow th-onclick events with strings.

Solution:
Remove foundation icons library (we weren't using that anyway)
Open new window with th:data-* attribute passed to javascript.

Fixed, done.

**Comment by zperova** [comment]
done
