### ISSUE TITLE
CV screening for interview

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#304]
### Description

As a PDX Finder developer, I want to have a competent Software Developer to join PDXFinder team.

### Acceptance criteria

- [x] @CsabaHalmagyi selected top 20 candidates
- [x] @zperova selected top 20 candidates

**Comment by zperova** [comment]
Hackerrank results finished September 8.
Carryover to the next sprint.

**Comment by CsabaHalmagyi** [comment]
This is now done.
