### ISSUE TITLE
Harmonize mouse strains for Curie-LC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#308]
### Description

The host strain nomenclature needs to be harmonized, so the same value would be used across mutations, cna, cyto and sampleplatform in the Curie-LC data.

Found values:
In sample platform: Crl:Nu(Ico)-foxn1nu(SWISS-NUDE)
In cyto: Crl:NU(NCr)-Foxn1n
In cna: Crl:Nu(Ico)-foxn1nu(SWISS-NUDE)
In mutation: Crl:Nu(Ico)-foxn1nu(SWISS-NUDE)

### Acceptance criteria:

- [x] "(SWISS-NUDE)" removed from all the entries

**Comment by zperova** [comment]
postponed until current sprint due to interviews

**Comment by zperova** [comment]
carry over to next sprint

**Comment by CsabaHalmagyi** [comment]
This is done now.

**Comment by zperova** [comment]
Perfect, thank you @CsabaHalmagyi
