### ISSUE TITLE
Invalid alt_allele value in Curie-LC mutation data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#309]
### Description

The mutation data contains "0" in the Alt column in five rows. These do not pass QC on the annotation pipeline.

https://app.zenhub.com/files/78657127/85fc0e4f-a57a-4062-8c63-1923a6a98095/download

@CsabaHalmagyi
This may be worth briefly mentioning with the provider if you do not know the origins of these bugs.

### Acceptance criteria
- [x] provider informed @zperova 
- [x] provider supplies correct values
- [x] values in the Curie-LC mutation data are corrected

**Comment by zperova** [comment]
@zperova to contact provider about the wrong values.

**Comment by zperova** [comment]
carry over to the next sprint

**Comment by zperova** [comment]
email sent

**Comment by zperova** [comment]
@CsabaHalmagyi I got a response from the provider - this is a deletion so there is no alternative allele. How do we model such cases?

**Comment by CsabaHalmagyi** [comment]
From the loading point of view this is fine, its the annotation pipeline that complains about the value. Thoughts @Afollet ?

**Comment by Afollet** [comment]
Short Answer: Annotation pipeline complains about the zero in the Alt Allele. Deletions are fine. Replace all the the '0' with '-'

Answer you didn't ask for:
VCF format anchors the deletion to the previous base pairs like
Ref: TC Alt: T

Ensembl format (what VEP takes and outputs):
Ref: C Alt:-

We VEP will digest the VCF format to VEP format.  The pipeline takes either, but you have to shift the bases to convert to VCF. So change the zeros to '-'.

**Comment by Afollet** [comment]
@zperova  I can make this changes and then annotated the data.

**Comment by zperova** [comment]
thank you @Afollet, also for the explanation.

**Comment by Afollet** [comment]
@zperova Done

**Comment by zperova** [comment]
Thanks @Afollet Closing.
