### ISSUE TITLE
Raw read submission -- VHIO-CRC

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#316]
VHIO-CRC contact, Lorena Ramirez, would like our help to broker submission of the 4 samples raw reads to the ENA. The data load is not large, but this is a great exercise for the PDX Finder to mature the brokering process.

Previous documents explaining the process are found with correspondance with PDMR:

https://docs.google.com/document/d/1LcCho6QALt06h1HsELPMIlyq2IStIOiyUU1_jfOi6Os/edit

### Acceptance criteria

- [x] obtain raw reads
- [x] create reusable documentation to explain submission to ENA
- [x] collaborate with VHIO-CRC to both explain and retrieve necessary data.
- [x] data successfully submitted
- [x] VHIO-CRC data linked to ENA on front end

**Comment by Afollet** [comment]
Some brief documents on ENA submission https://docs.google.com/document/d/1D1NHerVhzXFJtWLglj2Xm9-7y44KfJp8jCtpljDzTtw/edit

**Comment by Afollet** [comment]
Received everything necessary to submit sample metadata and Run/Experiment data models to ENA.

**Comment by Afollet** [comment]
Data submitted: 

Type	Accession	Unique Name
Study	PRJEB40666	ena-STUDY-EBI-05-10-2020-15:38:00:938-102
Sample	ERS5134615 (SAMEA7376174) 	HGP379.1 TUMOR CTAX2X11
Sample	ERS5134616 (SAMEA7376175) 	HGP397.1 TUMOR CTAX3X5
Sample	ERS5134617 (SAMEA7376176) 	HGP403.1 TUMOR M42X3
Sample	ERS5134618 (SAMEA7376177) 	HGP404.1 TUMOR M43X3
Experiment	ERX4580602	ena-EXPERIMENT-EBI-05-10-2020-15:37:56:618-1
Experiment	ERX4580603	ena-EXPERIMENT-EBI-05-10-2020-15:37:56:618-2
Experiment	ERX4580604	ena-EXPERIMENT-EBI-05-10-2020-15:37:56:618-3
Experiment	ERX4580605	ena-EXPERIMENT-EBI-05-10-2020-15:37:56:618-4
Run	ERR4656900	ena-RUN-EBI-05-10-2020-15:37:56:618-1
Run	ERR4656901	ena-RUN-EBI-05-10-2020-15:37:56:618-2
Run	ERR4656902	ena-RUN-EBI-05-10-2020-15:37:56:618-3
Run	ERR4656903	ena-RUN-EBI-05-10-2020-15:37:56:618-4

I will wait until the data is live in 48 hours to add the accessions to the sample platform. I estimate this will be a very minor task.

**Comment by Afollet** [comment]
@zperova done

**Comment by zperova** [comment]
thanks @Afollet
