### ISSUE TITLE
Annotate mutation data files for LIH

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#319]
### Description

As a PDXFinder developer I want to have all mutation files annotated in a harmonized fashion to ensure correct loading of data.

Related to https://app.zenhub.com/workspaces/pdxfinder-board-5f0f036188f27e0014a7bdfc/issues/pdxfinder/pdxfinder/276

### Acceptance criteria

- [x] mutation data is annotated

**Comment by Afollet** [comment]
This is my scientific curiosity:
![image.png](https://images.zenhubusercontent.com/5f0f06e30c4479013ba2ee38/197cd368-2d08-4d7f-b3b2-7e26a4f9dc97)

An Hg19 data point that is dropped when LiftOver to GRCh38. However, the data point is in an exon in TP53. Will post Biostar when I have free time and follow up.

**Comment by Afollet** [comment]
Data is annotated.

Set lost 23 data points do to them being "Intergenic" in addition to the data point above.

**Comment by Afollet** [comment]
Done

**Comment by zperova** [comment]
thanks @Afollet
