### ISSUE TITLE
Update PMLB cbio parser

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#322]
Previously, no HGNC symbols were found for the CNA data pulled from cbioportal.ca swagger API. To resolve this a service was designed to translate Entrez Gene ID's to HGNC since Entrez ID's were on the set. However a subset of the Entrez ID's could not be converted by the service.

Now, it has been found that the API allows for expanded details that includes the HGNC symbol. To parse these, the cbioportal json parser will need to be updated. This will allow us to retrieve these lost data sets for the current PMLB colon set and for a previously loaded set.

############ ACCEPTANCE CRITERIA#############
- [x] Correspond with HGNC to inquire about the missing Entrez Genes
- [x] Software as been updated to parse HGNC symbols
- [x] Software complete quality requirements and is pushed to Dev
- [x] PMLB cna is re-parsed for both current and previous sets.

**Comment by Afollet** [comment]
It's important to note that the HGNC set we are using is incomplete for Entrez Genes.

**Comment by Afollet** [comment]
Emailed and got a response for why our HGNC markers were not all mapping to Entrez

https://docs.google.com/document/d/1E4dpcCe0K6nCk2w9L1-RdU-75__Z047wpK3mWG4vDrs/edit?usp=sharing

**Comment by Afollet** [comment]
I need to write the test here to pass quality gates. Then this ticket will be done after populating the "omic" tsv's with information from the sample platform. See https://github.com/PDXFinder/pyData_Transformation/tree/master/populateOmicFromSamplePlatform

**Comment by Afollet** [comment]
@zperova done

**Comment by zperova** [comment]
this is great, thanks @Afollet
