### ISSUE TITLE
Mapping diagnosis for PMLB

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#331]
### Description

Inconsistent entry in the template:

![Screenshot 2020-10-02 at 14 13 15](https://user-images.githubusercontent.com/38244059/94927135-c5dd2f00-04b9-11eb-9eae-8fd0aa05aa11.png)

### Acceptance criteria

- [x] template corrected
- [x] mapping rules changes
- [x] db updated

**Comment by zperova** [comment]
Change to "recurrent" and "metastatic".
Need to investigate and plan for the future the allowed values and validation tool.

**Comment by zperova** [comment]
@zperova to do the mapping
@Afollet to change the template as described above
@CsabaHalmagyi to change mapping rules accordingly
@CsabaHalmagyi to reload the db

**Comment by zperova** [comment]
@Afollet @CsabaHalmagyi I can not see any mappings for this dataset

**Comment by CsabaHalmagyi** [comment]
This dataset has already been mapped, I can see pmlb rules with tumor type "metastases". I am updating the mapping rules.

**Comment by CsabaHalmagyi** [comment]
Updated the dataset and the mappinng rules accordingly.

**Comment by CsabaHalmagyi** [comment]
Updated h2 database with new rules

**Comment by zperova** [comment]
@Afollet some of the values for the tumour type now appear in capslock, could you please change the template to lower case? Thank you! Snapshot of the 1st page below: ![Screenshot 2020-10-14 at 16.07.28.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/75b85a03-4788-4464-a7f1-66c9ef9c0268)

**Comment by zperova** [comment]
or did this happen because of the rule changes @CsabaHalmagyi ?

**Comment by Afollet** [comment]
No, this is how the data. I fixed this in PMLB. Capitalization should be dealt with in the Updog. Along with trailing white spaces. These are both very easy things to implement.

**Comment by zperova** [comment]
eagle eye or X-ray vision @Afollet? I didn't see the trailing white spaces. Thank you for fixing it, and making the ticket for clean-up.

**Comment by Afollet** [comment]
No trailing spaces here. I just have not gotten over my last encounter with a trailing space :smile: Cheers!

**Comment by Afollet** [comment]
Will the mappings need to be fixed because of this, @CsabaHalmagyi ?

**Comment by zperova** [comment]
as discussed this will not affect the mapping. Closing as done
