### ISSUE TITLE
Add LIH IHC platform info

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#339]
### Description 

As a PDX Finder user I want to see the information about the LIH IHC platform used to generate data from the LIH models.

http://dev.pdxfinder.org/platform/lih-cyto/

### Acceptance criteria

- [x] request platform info from provider
- [x] update platform info

**Comment by zperova** [comment]
email sent

**Comment by zperova** [comment]
will not affect release as currently have a placeholder - will update at a later stage if do not receive the info from the provider in time.

**Comment by zperova** [comment]
IHC platform info received: https://docs.google.com/document/d/1XgBgQ4X0s3ePfJV4rajK1iNTHVUCNEbMXjugjR1Uiv0/edit
@CsabaHalmagyi

**Comment by CsabaHalmagyi** [comment]
Updated platform description.

**Comment by zperova** [comment]
thank you @CsabaHalmagyi Closing
