### ISSUE TITLE
xDog support Drug Dosing 

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#343]
XDog will need to be able to export drug dosing before PDXNet-HCM-BCM can be fully exported and the custom loader retired. 

####### ACCEPTANCE CRITERION ####### 

- [x] Changes made to xDog and validated
- [x] feature is fully test 
- [x] feature approved and pushed to Dev

**Comment by Afollet** [comment]
Merging from Alexs_custom_retirment_plan_with_the_xdog on gitlabe

**Comment by Afollet** [comment]
@zperova done

**Comment by zperova** [comment]
thank you @Afollet
