### ISSUE TITLE
Hide Curie-LC and Curie-BC molecular data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#350]
### Description

Request from provider to hide all the molecular data from:

Curie-LC
Curie-BC

### Acceptance criteria

- [x] data not visible in prod

**Comment by CsabaHalmagyi** [comment]
This dataset will be hidden when we do the release. Do I need to change the content of the previous release to hide the dataset on prod now or can it wait till we do the release? @zperova

**Comment by zperova** [comment]
@CsabaHalmagyi please hide the data in prod now. It can not wait until release and needs to be done ASAP.

**Comment by CsabaHalmagyi** [comment]
There are two different ways to hide Curie-LC and Curie-BC datasets:

Solution 1:
Connect to your production neo4j server (port 7474 by default) and run the following cypher query:

match (mod:ModelCreation)--(s:Sample)--(mc:MolecularCharacterization)
where mod.dataSource="Curie-LC" or mod.dataSource="Curie-BC"
set mc.isVisible=false

Solution 2:
Update the code responsible for setting the visibility https://github.com/PDXFinder/pdxfinder/blob/master/indexer/src/main/java/org/pdxfinder/postload/SetDataVisibility.java#L32
After row 32 include the following two rows:

applyDataVisibilityRules("Curie-LC");
applyDataVisibilityRules("Curie-BC");

Once this is done, reload the database as normal.

**Comment by CsabaHalmagyi** [comment]
This is done now.

**Comment by zperova** [comment]
thank you @CsabaHalmagyi for a timely fix!
