### ISSUE TITLE
Update LIH metadata

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#357]
### Description

As a provider, I want to see correct metadata supporting my datasets in the PDX Finder.

Recent metadata file: https://docs.google.com/spreadsheets/d/1GpHuIGH0IYUvShGWQH-Nfg_KXayBRcyg/edit#gid=608325760

### Acceptance criteria

- [x] metadata updated

**Comment by CsabaHalmagyi** [comment]
Updated the metadata and pushed it to the repo. This is done now.
