### ISSUE TITLE
Update Provider name - Pediatric Preclinical Testing Consortium

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#372]
### Description

Observed: Preclinical Pediatric Testing Consortium

Expected:  Pediatric Preclinical Testing Consortium

http://www.ncipptc.org/

### Acceptance criteria

- [x] Provider name changed in the db
- [x] changes are propagated to prod

**Comment by Afollet** [comment]
I made this change on the Dev branch of the DB

**Comment by zperova** [comment]
@Afollet could you please also check that it is American English, the original ticket I wrote corrected for British spelling.

**Comment by Afollet** [comment]
It is "Pediatric Preclinical  Tumor Consortium" in the database.

I only know American English @zperova

**Comment by zperova** [comment]
WIll go in with the next Release

**Comment by zperova** [comment]
@CsabaHalmagyi to update in the database on beat and live

**Comment by CsabaHalmagyi** [comment]
This is now done.

**Comment by zperova** [comment]
closing. Thanks @CsabaHalmagyi
