### ISSUE TITLE
Prepare EurOPDX data and instructions

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#375]
### Description

As a developer, I want to provide a comprehensive package for EurOPDX data release on EurOPDX Portal.

### Acceptance criteria

- [x] extract EurOPDX data from the repo
- [x] extract EurOPDX mappings from the repo in JSON
- [x] write instructions on how to deploy the application
- [x] write instructions on how to do the upgrade of software stack required for the new version 
- [x] do a test load of EuroPDX data to make sure it's working and deployable
- [x] data and instructions sent to EurOPDX

**Comment by CsabaHalmagyi** [comment]
EuroPDX data and corresponding mappings were exported from repo.

**Comment by zperova** [comment]
moved to the next sprint

**Comment by CsabaHalmagyi** [comment]
My part is done, document:
https://docs.google.com/document/d/1_B9Y4a-QT03sKhq6f1m-Az-kRPt7ZWivANzyVXO0laI/edit#
It's all yours now, @zperova
