### ISSUE TITLE
Onboarding Mauricio

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#377]
### Description

Onboarding document here: https://docs.google.com/document/d/1ZZbv7QvTmQAk5xvkDWk4Eepxsr_rY7qhQRj4PuRSY_Y/edit#

### Acceptance

- [x] all tasks necessary are in the doc
- [x] Zina to make a ticket for Mauricio

**Comment by CsabaHalmagyi** [comment]
Added a few links and bulletpoints to the document.

**Comment by zperova** [comment]
@zperova to close once done

**Comment by zperova** [comment]
made specific tickets
