### ISSUE TITLE
Query details on existing data from all providers

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#380]
### Description

As a developer, I want to query details of existing data from providers to check it's in line with the provider's expectations.

List of contacts to include:
provider
number of submitted models
diagnosis
tumour site
tumour type
contact
email

Folder for the query results here: https://drive.google.com/drive/folders/1NUk9ZH0FKGAZFU2c5Ecavyu-uwSROhzO

### Acceptance criteria

- [x] a list of contacts as described above in Google drive @CsabaHalmagyi

**Comment by CsabaHalmagyi** [comment]
I started working on this. Not every provider has emails, some use contact form urls. To this I am also going to include the mapped diagnosis term and construct the url to the model in the finder.

**Comment by CsabaHalmagyi** [comment]
Query for future purposes

```
match (ps:PatientSnapshot)--(s:Sample)--(mod:ModelCreation) with distinct s, mod
optional match (s)--(ot:OntologyTerm)
optional match (tt:TumorType)--(s)-[:SAMPLE_SITE]-(pt:Tissue)
optional match (mod)--(eu:ExternalUrl{type:"contact"})
return distinct mod.dataSource as DataSource, mod.sourcePdxId as ModelId, s.diagnosis as Diagnosis, 
ot.label as MappedTerm, tt.name as TumorType, pt.name as PrimaryTissue, 
collect(eu.url) as Contacts, "https://www.pdxfinder.org/data/pdx/"+mod.dataSource+"/"+mod.sourcePdxId as PdxFinderUrl
```

**Comment by zperova** [comment]
@zperova to split this into 2 separate tickets

**Comment by CsabaHalmagyi** [comment]
Data exported and uploaded to drive.

**Comment by zperova** [comment]
done
