### ISSUE TITLE
Decouple h2 db from indexer

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#385]
### Description

As a developer, I want to be able to decouple h2 db from Admin UI.

### Acceptance criteria

- [x] h2 db decoupled from indexer

**Comment by zperova** [comment]
This is a complex task, requires changes in the indexer and changes in the Admin Interface

**Comment by zperova** [comment]
moving to the next sprint, adding @mauroz77

**Comment by zperova** [comment]
2 requirements for this: 
- API service and tests
- Admin UI is deployed from the main repository. Need to decide how to deploy front-end separately from the back-end: https://github.com/PDXFinder/pdxfinder/issues/443

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
moving to the next sprint as still blocked

**Comment by zperova** [comment]
Taken the new local solution for the Admin UI, this now can be done.

**Comment by CsabaHalmagyi** [comment]
Removed H2 interaction from the indexer.

**Comment by CsabaHalmagyi** [comment]
Done.

**Comment by zperova** [comment]
Hurray!
