### ISSUE TITLE
Onboarding process for Mauricio

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#390]
### Description

Welcome to PDX Finder! Below are the useful links for the resource
Useful links:

PDXFinder: https://www.pdxfinder.org/

Google Drive:  https://drive.google.com/drive/folders/0AKfN-7HjRxNGUk9PVA

Github: https://github.com/PDXFinder/

GitLab: https://gitlab.ebi.ac.uk/mouse-informatics/pdxfinder-data

Confluence: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/PDXFinder

Patient-Derived Cancer Models (PDCM) Grant 2020-2025: https://docs.google.com/document/d/10IVeKX8KM0fkYNLA-t2ag7uhvT1n6LAB5U9T4vpj7bE/edit

### Onboarding meetings:
Please book in the PDX Project Google calendar and tick off once done

Neo4j:  Csaba
- [x] Introduction to graph databases
- [x] Cypher
- [x] Project specific queries
- [x] Neo4j server vs embedded driver
- [x] Domain model

Data: Alex
- [x] Data templates
- [x] Data repo ( SSH keys need to be setup)
- [x] Data directory structure
- [x] How to update the data, aka best practices 
- [x] Data ingress, what can go wrong

PDXFinder: Csaba
- [x] Data loading
- [x] Data harmonization and mapping
- [x] The webapp
- [x] The admin UI
- [x] What runs where? (+ Zina)
- [x] Steps to take to prevent an armageddon (+ Zina)

Work practices: Zina - 1 hr total
- [x] Github repo and issues
- [x] Sprints
- [x] Google Drive
- [x] PDX Finder Dev call with Jax colleagues
- [x] Timesheets
- [x] Activity reports in Confluence
- [x] Documentation
- [x] Intro to JAX colleagues - Thursday Nov 12

### Acceptance criteria

- [x] all meetings and tasks done

**Comment by CsabaHalmagyi** [comment]
![autodraw 12_11_2020-2.png](https://images.zenhubusercontent.com/5f156562d7f33214f282c3f7/d91df332-6ca1-41e4-848c-3a637d2371fa)

**Comment by zperova** [comment]
moving to the next sprint

**Comment by mauroz77** [comment]
@zperova done

**Comment by zperova** [comment]
thanks, closing now.
