### ISSUE TITLE
Onboarding Mauricio - Alex

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#391]
### Description

Meetings to have with Mauricio

Data:
- [x] Data directory structure, what is where and naming conventions
- [x] Brief explanation on data sheet types

GitLab:
- [x] SSH Keys are setup and access is granted to gitlab.ebi.ac.uk
- [x] Brief show of CI/CD and how it works in the data repository
- [x] How to clone repository, commit and push

Domain and Validation:
-  [x] How the domain is capture in .tsv
-  [x] How the molecular data is represented in TSV
-  [x] What can go wrong in loading

### Acceptance criteria

- [x] all meetings took place
- [x] necessary links/docs provided

**Comment by zperova** [comment]
moving to the next sprint

**Comment by Afollet** [comment]
@zperova done

**Comment by zperova** [comment]
thanks!
