### ISSUE TITLE
Onboarding Mauricio - Csaba

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#392]
### Description

Meetings to have with Mauricio

Neo4j:  
- [x] Introduction to graph databases
- [x] Cypher
- [x] Project specific queries
- [x] Neo4j server vs embedded driver
- [x] Domain model

PDXFinder: 
- [x] Data loading
- [x] Data harmonization and mapping
- [x] The webapp
- [x] The admin UI
- [x] What runs where? (+ Zina)
- [x] Steps to take to prevent an armageddon (+ Zina)

### Acceptance criteria

- [x] all meetings took place
- [x] necessary links/docs provided

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
This is done now.
