### ISSUE TITLE
Extend Validator for additional validation rules

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#395]
As a developer, I want to have features completed in the validator so It can be used.

Additional rules ideas: Ideas for additional rules: https://docs.google.com/document/d/1ieaYamxzO5E71MCXxIQXqD6EohziGvZzLiH3TG3gjVo/edit

For key features have been determined:
1. One-to-many relationship validation
I.E. A patient sample can only be linked to one patient. A model can only be linked to one patient sample. 
2. Character set restriction -- be able to set character set restrictions for the specific columns
3. Value restrictions -- be able to set value set restriction for specific columns
4. Verbose mode toggle by argument
5. Cleaning the validator to differentiate between "ERROR" and "WARNING" 
6. Clean trailing spaces from strings (TableSetCleaner functionality)

########## ACCEPTANCE CRITERIA ##############

- [x] update database cleaning to lowercase (on specific columns) and trim strings

- [x] code feature for one-to-many restriction
- [x] clarify host strain nomenclature rule.
- [x] implement character set restriction 
- [ ] implement value restriction
- [ ] clean log levels
- [ ] create implement verbose mode 

- [ ] quality gates are met

**Comment by zperova** [comment]
moving to the next sprint

**Comment by Afollet** [comment]
Merged lower casing and trimming to dev.

Starting to work on one-to-many restriction and one-to-one restriction.

**Comment by Afollet** [comment]
Currently adding a validation of relationships that uses the following definitions:



    “one_to_one” or “1:1”: check if merge keys are unique in both left and right datasets.

    “one_to_many” or “1:m”: check if merge keys are unique in left dataset.

    “many_to_one” or “m:1”: check if merge keys are unique in right dataset.

    “many_to_many” or “m:m”: allowed, but does not result in checks.

**Comment by Afollet** [comment]
Retiring ticket in favor of #440, #441 and #442

**Comment by Afollet** [comment]
@zperova Closing
