### ISSUE TITLE
Metadata value restriction map

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#396]
### Description

As a developer, I would like the metadata value and character restrictions to be clear determined so that I can write validation software for the metadata associated spreadsheets.

every column has determined values and character set (if free text). I.E. for  tumour_type  can be "metastasis/recurrent/local relapse"  At the minimum: "any characters, free text". This should include possible missing value entries or "" if allowed to be blank.

More sophisticated rules for the columns can be made if necessary and should be recorded for future implementation into the validator.

Missing values should be considered as well: https://ena-docs.readthedocs.io/en/latest/submit/samples/missing-values.html?highlight=INSDC

A gDoc to host and share these rules internally for tumor type: https://docs.google.com/spreadsheets/d/1VWxvqvJej-Eq1UQirYh2u_VyndQaaTPlEj0keMsKZ88/edit#gid=0

Ongoing exploration and explanation of metadata.xslx rules: https://docs.google.com/document/d/1ieaYamxzO5E71MCXxIQXqD6EohziGvZzLiH3TG3gjVo/edit

Metadata WorkSheet: https://docs.google.com/spreadsheets/d/1qswBH0CztGrIM5OBT8mCQYeQ7ylWjoLIvnm50x2wuFc/edit#gid=0

### Acceptance criteria

- [x] gDoc is created to mirror metadata.xlsx and linked in ticket
- [x] every column has set values

**Comment by Afollet** [comment]
Very basic first pass has been completed the restriction map.

**Comment by zperova** [comment]
done
