### ISSUE TITLE
Links to OncoMX are not displayed

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#404]
### Description

Links to OncoMX are not displayed, while the links for the other external resources are there.  

![Screenshot 2020-11-17 at 15 58 35](https://user-images.githubusercontent.com/38244059/99525223-71224480-2991-11eb-8af9-a7c4f9ce079d.png)

### Acceptance criteria:

- [x] identify what link was used to link resources
- [x] fix the link

**Comment by Afollet** [comment]
As discussed, this is a failure of the micro-service. No links are being generated by the PDX-Gun

**Comment by Afollet** [comment]
I would like to document this solution briefly before this ticket is closed.

I made a ticket for future work on the Hasura pod: #455

**Comment by zperova** [comment]
@Afollet very good idea to document! Will it live on Confluence?

**Comment by Afollet** [comment]
Here it is https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=140902758

This ticket is ready to close @zperova

**Comment by zperova** [comment]
closing.
