### ISSUE TITLE
Enable front-end changes for Admin UI to do mappings independently

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#408]
### Description

As a developer, I want to do mappings independently in Admin UI.

Required back-end change and front-end change

### Acceptance criteria

- [x] front-end change done

**Comment by mauroz77** [comment]
PR created: https://github.com/PDXFinder/pdx-admin-ui/pull/2

**Comment by mauroz77** [comment]
@zperova: done. The button is already added to the ui. This was done in a new dev branch and it's not yet deployed, so still not visible in the admin ui in http://ves-ebi-bc.ebi.ac.uk:8081/

**Comment by zperova** [comment]
thanks @mauroz77 Closing
