### ISSUE TITLE
Upgrade Angular version in pdx-admin-ui

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#411]
As a developer, I want to have an angular version up to date, that allows me to make use of improved functionalities and that it's easier to maintain.

The current versions for Angular and Angular CLI in the project are:

Angular CLI: 8.3.29
Angular: 8.2.14

And the latest versions available are:
Angular CLI: 11.0.1
Angular: 11.0.0

This information can be retrieved with the command:
`ng --version`

**Comment by zperova** [comment]
still blocked, moving to the next sprint

**Comment by mauroz77** [comment]
@zperova done

**Comment by zperova** [comment]
thanks, well done @mauroz77
