### ISSUE TITLE
Fix lint issues in admin ui project

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#417]
### Description

As a developer, I want to keep the project free of lint errors/warnings.

Currently, executing a static code analysis in the admin ui project reports several errors, as listed in the attached file. [https://app.zenhub.com/files/78657127/abd09046-6cf8-4be7-a3b5-37a2b53c84a4/download](https://app.zenhub.com/files/78657127/abd09046-6cf8-4be7-a3b5-37a2b53c84a4/download)

### Acceptance criteria
- [x] Project does not have more lint errors

**Comment by mauroz77** [comment]
Found additional errors while running locally the command:
`
ng lint && npm audit && ng build --prod
`
Errors are listed in the attached file.[https://app.zenhub.com/files/78657127/1312a7e7-67fb-4228-80ca-8e68ae91872a/download](https://app.zenhub.com/files/78657127/1312a7e7-67fb-4228-80ca-8e68ae91872a/download)

**Comment by mauroz77** [comment]
@zperova Done. Currently the project passes the lint analysis and also the audit analysis (Auditing package dependencies for security vulnerabilities)

**Comment by zperova** [comment]
thanks @mauroz77 Closing.
