### ISSUE TITLE
Fix Data summary page for TRACE

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#419]
### Description

Something is wrong:
- either the data type
- or there is no sequencing platform and it somewhere crept in

![Screenshot 2020-11-23 at 16 23 25](https://user-images.githubusercontent.com/38244059/99989308-5cd3b280-2daa-11eb-9630-0799089fa448.png)

### Acceptance criteria

- [ ] fixed

**Comment by zperova** [comment]
For FISH model_ID: BRC0021PR
For sequencing model_ID:

**Comment by CsabaHalmagyi** [comment]
Data fixed on dev:

https://dev.pdxfinder.org/source/trace/
Chart fixed on cms:
https://cms.pdxfinder.org/source/trace/

The two changes together will fix prod.

**Comment by zperova** [comment]
Great, thanks@
