### ISSUE TITLE
Fix Data summary page for JAX

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#420]
### Description

Many links are missing, names for the Platform are non-informative and confusing.

![Screenshot 2020-11-23 at 16 36 47](https://user-images.githubusercontent.com/38244059/99989720-dff50880-2daa-11eb-9854-852512f47f6b.png)

### Acceptance criteria

- [ ] platform renamed according to harmonized names
- [ ] all the links provided

**Comment by zperova** [comment]
Protocols are here: https://drive.google.com/drive/folders/1tm0hyfHaBSezcaLCTZEJYxXnSIYjJyPh

**Comment by zperova** [comment]
Confusing names we will deal with later.

**Comment by zperova** [comment]
@zperova to create WP pages first

**Comment by CsabaHalmagyi** [comment]
Exported the platform names that needs to have a placeholder page in wp.

**Comment by CsabaHalmagyi** [comment]
Created sampleplatform file and included the new urls provided by Zina. This is done now.
