### ISSUE TITLE
Fix Data Summary for MD Anderson

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#421]
### Description

Cancer by system pie chart is not working. There are 316 models.

![Screenshot 2020-11-23 at 16 43 40](https://user-images.githubusercontent.com/38244059/99989998-32cec000-2dab-11eb-9550-749975af4db2.png)

### Acceptance criteria

 - [ ] pie chart displays data

**Comment by CsabaHalmagyi** [comment]
The data available chart is correct, since we do not have any molecular/drug dosing data associated with this dataset.

**Comment by CsabaHalmagyi** [comment]
The chart is now fixed on cms:

https://cms.pdxfinder.org/source/mdanderson/

**Comment by zperova** [comment]
great, thanks!
