### ISSUE TITLE
Fix Data Summary page for Wistar/MD Anderson/Penn

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#422]
### Description

Cancer by system pie chart is not working. There are 256 models.
![Screenshot 2020-11-23 at 16 46 46](https://user-images.githubusercontent.com/38244059/99990292-8e00b280-2dab-11eb-9f7b-d3ea7415f201.png)

### Acceptance criteria

 - [x] pie chart displays data

**Comment by CsabaHalmagyi** [comment]
Fixed this on cms and removed data available tab since no molecular/drug data is associated with the dataset.
https://cms.pdxfinder.org/source/wistar-mdanderson-penn/

**Comment by zperova** [comment]
great, thanks!
