### ISSUE TITLE
Fix Data Summary for WUSTL

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#423]
### Description

Cancer by system pie chart is not working. There are 119 models.

![Screenshot 2020-11-23 at 16 48 35](https://user-images.githubusercontent.com/38244059/99990516-cef8c700-2dab-11eb-97d4-583cabd0a67d.png)

### Acceptance criteria

 - [x] pie chart displays data

**Comment by CsabaHalmagyi** [comment]
Fixed cancer by system and removed data available chart.
https://cms.pdxfinder.org/source/wustl/

**Comment by zperova** [comment]
great, thanks!
