### ISSUE TITLE
Fix Data summary for HCI-BCM

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#424]
### Description

Cancer by system pie chart is not working. There are 51 models.

![Screenshot 2020-11-23 at 16 50 29](https://user-images.githubusercontent.com/38244059/99990698-0ebfae80-2dac-11eb-88c0-70347c9b02a7.png)

### Acceptance criteria

 - [x] pie chart displays data

**Comment by CsabaHalmagyi** [comment]
Fixed piechart on:
https://cms.pdxfinder.org/source/hci-bcm/
Done.

**Comment by zperova** [comment]
thanks @CsabaHalmagyi
