### ISSUE TITLE
Display total number of models on the Provider page

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#425]
### Description

As a user, I want to see the total number of models from the Provider page, instead of going back to the landing page to do that.

### Acceptance criteria

-  [ ] the total number of models displayed on the Provider page

**Comment by CsabaHalmagyi** [comment]
Created a function to determine the provider abbrev from the url.

**Comment by CsabaHalmagyi** [comment]
Updated all provider pages with the script.

**Comment by CsabaHalmagyi** [comment]
Done.
