### ISSUE TITLE
Fix provider name for PPTC

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#426]
### Description

PPTC name is incorrect in the Provider list on the landing page:

![Screenshot 2020-11-24 at 10 19 00](https://user-images.githubusercontent.com/38244059/100081214-ac63be00-2e3e-11eb-8f9b-e688076fabd1.png)

should say: Pediatric Preclinical Testing Consortium

### Acceptance criteria:

- [x] fixed in dev

**Comment by CsabaHalmagyi** [comment]
Name fixed on all instances.
