### ISSUE TITLE
Add travis configuration for pdx-admin-ui

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#430]
### Description
As a developer I want to have an automatic way to check code quality

### Acceptance Criteria
- [x] A travis job is started whenever a PR is created in the repository

**Comment by mauroz77** [comment]
@zperova Done. Now every time a PR is created, the code will be automatically analysed to check that there are not lint errors or security problems in the dependencies due to the new code.

**Comment by zperova** [comment]
thanks @mauroz77 Closing.
