### ISSUE TITLE
Remove incorrect publication for TRACE platform

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#433]
### Description

As reported by a provider, incorrect publication is linked to the following model: BRC0004PR.
Looks like this publication is linked to other models as well. 

### Acceptance riteria

- [x] publication has been removed

**Comment by CsabaHalmagyi** [comment]
After doing some investigation I identified that this is a bug and not a data issue. There is a publication group with pubmedId = "not specified" and this text is being translated as a number which then is being used as an ID to the publication. We shouldn't be creating this group in the first place, so this requires some changes in the data loader.

Currently we have 624 models linked to this publication (basically all models are linked to this that were using "not specified" for the pubmed id). 

I need to put together a query to remove this group and all its relationship from the database. This will fix the data in prod, but before the next release the data loader should be updated not to create this group.

**Comment by CsabaHalmagyi** [comment]
Example models that are affected by this bug:

http://pdxfinder.org/data/pdx/CRL/CRL-2304

http://www.pdxfinder.org/data/pdx/TRACE/BRC0004PR

**Comment by CsabaHalmagyi** [comment]
I removed the mentioned node from the databases (dev, beta and prod). Done, but created a ticket for the additional work: #437

**Comment by zperova** [comment]
Great, thanks @CsabaHalmagyi Provider has been now informed about the fix.
