### ISSUE TITLE
Fix display of variants in Gene Mutation filter box

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#435]
### Description

To reproduce:
Go to Search, choose Gene expression, type gene name (e.g. KRAS), click on Variant. 
Observed:
![Screenshot 2020-11-30 at 14 27 37](https://user-images.githubusercontent.com/38244059/100622684-0d950100-3319-11eb-94b4-7ed18b81e47a.png)
Expected:
a list of variants to choose from or Pick all option

### Acceptance criteria

- [x] drop-down window displaying variants is  fixed

**Comment by zperova** [comment]
will check dev for any features, if not will make fix in beta and merge back to dev, and do release to prod

**Comment by CsabaHalmagyi** [comment]
This issue is related to the upgraded Thymeleaf engine. Thymeleaf 3 doesn't allow the usage of th events anymore, these should be defined as attributes.

**Comment by CsabaHalmagyi** [comment]
This is now fixed on dev but the fix cannot be applied to beta/prod until system solves the current VM issue.

**Comment by CsabaHalmagyi** [comment]
Pushed to prod. We have some permission issues with the failover server, so the update didn't make it there.

**Comment by CsabaHalmagyi** [comment]
The issue with permissions on the failover still exists. Contacted support.

**Comment by zperova** [comment]
closing this, will make a new ticket for the deployment of the failover server
