### ISSUE TITLE
Validator Log cleaning and reability

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#441]
As a user of the validator, I would like to be able to quickly tell what is needs to be fixed with my data set.

Log errors in the validator tend to all "ERROR" while some are strictly informational. The validator should only return "ERROR" information where something is known to be incorrect.

####### ACCEPTANCE CRITERIA #########

-- [X] validator logs have been cleaned to ensure readability
-- [X] validator logs are only raising ERROR

**Comment by zperova** [comment]
done, closing
