### ISSUE TITLE
Validator -- advance error detection

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#442]
As a user, I want to know when my submitted data errors are clearly flagged.

PDX Finder table specifications can be extended to include:
* Unique combination ( For use on Model page and potentially sample)
* Require Filled relation ( Use for when the one column requires a non-blank entry in another column EG Grade requires a grading system. Also Collection Event if sample is not unique)
*ElseThen Relation ( test a relation if the first relation fails to validate)

######## ACCEPTANCE CRITERIA #########
- [ ] features planned
- [ ] implemented, test, merged
- [ ] logs cleaned

**Comment by Afollet** [comment]
I do not think these are any longer relevant to the project @zperova

**Comment by zperova** [comment]
Relevant features have already been implemented. Closing this ticket as no longer needed.
