### ISSUE TITLE
Research containerization options for PDX Finder

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#444]
### Description 

As a developer, I want to have a containerization strategy for the PDX Finder services.

### Acceptance criteria

- [x] plan in place

**Comment by Afollet** [comment]
1. Containerization for a micro-service is the way to go
2. There might be other ways to deploy a micro-service besides the Embassy Hosted Kubernetes cluster, but am not sure they are supported by TSC.
3. Kuberentes will allow for flexible deployment options both for internal and internet facing services. We will be able to scale on demand and to roll over services with no down time. 
4. The patterns for deployment are already largely in place. The PDX-Gun and other projects in Mouse Informatics already have deployed to Kuberentes. It will be easy to copy these deployments and quickly deploy new services.
5. Other options may be available, but this may be the path of least resistance for PDX Finder.

**Comment by zperova** [comment]
the plan is in place, followed up with a separate deployment ticket
