### ISSUE TITLE
Explore HCMI Searchable catalog code

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#445]
### Description

As a developer, I want to understand how the HCMI Searchable Catalog works to reuse any useful functionality for extended PDX Finder. 
Explore: 
https://github.com/nci-hcmi-catalog

### Acceptance criteria

- [x] pull out a list of attributes used for cell lines and organoids
- [x] analysis of features 
- [x] analysis of technologies

**Comment by Afollet** [comment]
[https://app.zenhub.com/files/78657127/9550fb71-0634-4ec4-8cdb-47800f5f36db/download](https://app.zenhub.com/files/78657127/9550fb71-0634-4ec4-8cdb-47800f5f36db/download)[https://app.zenhub.com/files/78657127/6585a6d4-9388-45d6-970e-7f7f486df57b/download](https://app.zenhub.com/files/78657127/6585a6d4-9388-45d6-970e-7f7f486df57b/download)

**Comment by zperova** [comment]
@CsabaHalmagyi to estimate the task

**Comment by CsabaHalmagyi** [comment]
https://hcmi-searchable-catalog.nci.nih.gov/

**Comment by zperova** [comment]
@CsabaHalmagyi could you please use this location for any results of this ticket: https://drive.google.com/drive/folders/1XAzy99bLa2nuZA970BaUIq0rvUdMQyWy Thank you!

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Attribute list document created:
https://docs.google.com/spreadsheets/d/1UxiOhzeH3KCJvm4_L3o1StYiyEcfXRHvirxiQUuaOrs/edit#gid=0
