### ISSUE TITLE
Clean blank strings from Database

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#446]
As a user, I would like my data to be validated consistently.

A column will not be labeled with empty if it consists of a " " space in each of the columns. However it should be marked as absent and currently the validator does not flag that these columns are missing.

####### ACCEPTANCE CRITERIA ##########
- [ ] Table cleaner removes blanks strings
- [ ] Validator will claim completely empty columns as missing even if they previously only contains strings
- [ ] tested and merged.

**Comment by zperova** [comment]
closing as no longer relevant
