### ISSUE TITLE
Front End Casing

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#449]
As a user, I want the front end to have formatted strings.

Because the database has now been harmonized to lower-case strings a few unformatted strings on the front end have changed.

In particular, the acronym underneath the Model Id:
http://dev.pdxfinder.org/data/search

This should be an easy CSS fix

###### ACCEPTANCE CRITERIA ########
- [x] CSS has been changed 
- [x] changes merged with dev

**Comment by mauroz77** [comment]
@zperova could you please give an example of the expected case formatting. For example for the 2 acronyms bellow, which should be the new value?
uoc-bc --> ?
JAX --> ?

Thanks.

**Comment by zperova** [comment]
@mauroz77 UoC-BC and JAX for the remaining abbreviations of the providers you can also check on prod instance - those are all correct there.
let me know if there are any other uncertainties.

**Comment by mauroz77** [comment]
Thanks @zperova . Just for the record, in prod UoC-BC is all upper case (UOC-BC). Should we just uppercase then? 
In prod we also have values like:

- Wistar-MDAnderson-Penn  
- MDAnderson

Which will be transformed to 
- WISTAR-MDANDERSON-PENN  
- MDANDERSON

Would that be ok?

**Comment by zperova** [comment]
Agreement on turning off Upper casing for Datasource abbreviation.

**Comment by zperova** [comment]
Tumour type and patient details still need to have casing fixed. @zperova check and make a list for @mauroz77

**Comment by Afollet** [comment]
I am turning of lower casing for the provider abbreviation.

I think it might be best to turn it off for host strain name and the stage columns. Both of these columns need more than simple casing rules to format the strings correctly. For example string "IcrTac:ICR-Prkdcscid" and "t2,n1,m0", respectively.  I hope by turning off lower casing for these columns that the majority of these string are formatted correctly in the template files. Therefore, giving an overall better presentation on the front end.

I've made the changes. Let me know if you would like me to do otherwise

**Comment by Afollet** [comment]
Alright, I merged these changes to Dev.

**Comment by mauroz77** [comment]
@zperova the css changes are merged. Next step, after I have the list of fields we want to uppercase, is to apply the css to them.

**Comment by zperova** [comment]
Fields to uppercase:
Irrespective of where the following values are: Not specified, Not available, Not provided

In Search results:
Histology, Primary, Collection, Type

In PDX Model:
Site, Type, Material, Material Status, 
Technique, Description


In Patient:
Sex, Ethnicity
Diagnosis, Type, Collection site
Regimen, Best response

In Molecular Data:
Sample type, Engrafted tumour passage, Data type

In Dosing study:
Drug, Response

**Comment by mauroz77** [comment]
@zperova done

**Comment by zperova** [comment]
Fields to capitalize:
In Search results:
Histology, Primary, Collection, Type

In PDX Model:
Site, Type, Material, Material Status,
Technique, Description

In Patient:
Sex, Ethnicity
Diagnosis, Type, Collection site
Regimen, Best response, Duration
Grade, Stage

In Molecular Data:
Sample type, Engrafted tumour passage, Data type

In Dosing study:
Drug, Response
