### ISSUE TITLE
Migrate all relevant repos from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#450]
### Description

As a developer, I want to ensure Travis CI works properly after it's migration announced to happen "no later than 31 December 2020".

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

### Acceptance criteria

- [x] all relevant repos migrated to travis-ci.com

**Comment by mauroz77** [comment]
Migrated the following repos:

- pdx-admin-ui
- pdx-data-core
- pdxfinder
- pdx-ontology

**Comment by mauroz77** [comment]
@zperova done
