### ISSUE TITLE
Fix error when querying H2 database with multiple statuses as filters

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#452]
### Description ###
The search method provided by the Mapping Service in pdx admin backed accepts several filters, among them the status of the mappings.
That filter can accept several values, and this causes an issue when running the final query.

For instance, calling this endpoint:
http://localhost:8081/api/mappings?mq=datasource:ircc-gc&entity-type=diagnosis&status=created,validated

Leads to the error:

> org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "VARCHAR to ROW"; SQL statement:
select distinct mappingent0_.entity_id as entity_i1_3_, mappingent0_.date_created as date_cre2_3_, mappingent0_.date_updated as date_upd3_3_, mappingent0_.entity_type as entity_t4_3_, mappingent0_.justification as justific5_3_, mappingent0_.map_type as map_type6_3_, mappingent0_.mapped_term_label as mapped_t7_3_, mappingent0_.mapped_term_url as mapped_t8_3_, mappingent0_.mapping_key as mapping_9_3_, mappingent0_.status as status10_3_ from mapping_entity mappingent0_ inner join mapping_values mappingval1_ on mappingent0_.entity_id=mappingval1_.mapping_entity_id where (lower(mappingent0_.entity_type) in (?) or ?='0') and (lower(mappingval1_.mapping_values_key)=lower(?) and (lower(mappingval1_.mapping_values) in (?)) or ?='0') and (lower(mappingent0_.mapped_term_label)=lower(?) or ?='') and (lower(mappingent0_.map_type)=lower(?) or ?='') and (lower(mappingent0_.status) in (? , ?) or (? , ?)='0') and (?='' or mappingent0_.map_type is not null) order by mappingent0_.entity_id asc limit ? [22018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]

### Acceptance Criteria ###
- [x] Fix the error so the service handles correctly filters with several values in the status.

**Comment by zperova** [comment]
done
