### ISSUE TITLE
Fix age filter

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#459]
### Description

NCI defines pediatric as "from birth to 15 years old". We need to reflect this with our age filter.

https://www.cancer.gov/publications/dictionaries/cancer-terms/def/pediatric-cancer

### Acceptance criteria

- [x] age filter fixed

**Comment by CsabaHalmagyi** [comment]
Replaced 10-19 age bin with 10-15 and 16-19. Done.

**Comment by zperova** [comment]
Great, thanks @CsabaHalmagyi
