### ISSUE TITLE
Install Java 11 on bc, b4 and prod servers

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#462]
### Description

As a developer, I want to have Java 11 on all the servers.

### Acceptance

- [x] installed on bc
- [x] installed on b4
- [x] installed on prod

**Comment by zperova** [comment]
waiting for systems to mount. If does not happen by the end of this week, @CsabaHalmagyi will manually install JAVA on all the machines.

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Java 11 is installed on BC, dev reloads fine.

**Comment by CsabaHalmagyi** [comment]
Java 11 is accessible on BETA.

**Comment by CsabaHalmagyi** [comment]
This is FINALLY done. 
Given that we are using different file systems, I created a confluence page documenting the path to the different installations here:
https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Java+11+installation+locations

**Comment by zperova** [comment]
Great, thanks @CsabaHalmagyi
