### ISSUE TITLE
Redeploy failover server

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#463]
### Description

As a developer, I want to redeploy the failover server to ensure recent fixes are everywhere.

### Acceptance criteria

- [x] failover server redeployed
- [x] gene filter is working on the failover server

**Comment by CsabaHalmagyi** [comment]
I contacted systems again since we still do not have the appropriate permissions set for the failover server.

**Comment by CsabaHalmagyi** [comment]
This is now fixed.

**Comment by zperova** [comment]
Thanks!
