### ISSUE TITLE
Clean-up data values for the release

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#468]
### Description 

As a developer, I want to clean-up all the errors identified by the validator tool.

### Acceptance criteria

- [x] all validator reports have been reviewed and data cleaned

**Comment by zperova** [comment]
This ticket needs to be broken up once the validator has been run on all datasets.

**Comment by zperova** [comment]
Results of the validator are here: https://app.zenhub.com/workspaces/pdxfinder-board-5f0f036188f27e0014a7bdfc/issues/pdxfinder/pdxfinder/497

**Comment by zperova** [comment]
Here are the suspects. Error count/provider. The count is subject to change:
1 provider [UMCG]
2 provider [NKI] @Afollet 
3 provider [Curie-BC]
4 provider [Curie-LC]
5 provider [Curie-OC]
5 provider [IRCC-GC]
6 provider [IRCC-CRC]
6 provider [UOM-BC]
6 provider [VHIO-BC]
7 provider [LIH]
7 provider [PMLB] @Afollet 
7 provider [UOC-BC]
7 provider [VHIO-CRC]
9 provider [HCI-BCM]
10 provider [VHIO-PC]
12 provider [PDMR] @Afollet 
12 provider [SJCRH]
13 provider [CRL]
14 provider [PPTC] @Afollet 
14 provider [WUSTL]
17 provider [MDAnderson]
18 provider [DFCI-CPDM]

**Comment by mauroz77** [comment]
Things to check:

- It seems like numeric sample_id (sample sheet) values are not recognised. Reported as "Missing value(s) in row numbers..."

**Comment by Afollet** [comment]
Thanks @mauroz77 
I have made the same observations. I appears that the jtablesaw library is reading in the table and replacing the numeric types with blanks. If you use the "TYPE" function in excel you can see the cell value types are different. I'mma going open an issue on the jtablesaw repo about this.

**Comment by zperova** [comment]
This ticket is related to the clean-up: https://app.zenhub.com/workspaces/pdxfinder-board-5f0f036188f27e0014a7bdfc/issues/pdxfinder/pdxfinder/362

**Comment by Afollet** [comment]
I have resolved all the tumour_type changes besides for 
Jax,
DFCI-CPDM
Everything that has "not specified" as a tumour_type

I changed all the mappings to correspond with these tumour_type changes.

**Comment by zperova** [comment]
@Afollet I take it as I can start mapping now?

**Comment by Afollet** [comment]
@zperova I checked the mappings yesterday. There was not anything new. Is there suppose to be new mappings?

**Comment by zperova** [comment]
I thought there will be about 30 mappings to do @CsabaHalmagyi was talking about - possibly from JAX

**Comment by Afollet** [comment]
I have a few changes on my local machine that I will push when gitlab is running.

There are correspondence between PPTC and DFCI-CPDM ( as @mauroz77 said ), but the rest of the work has been done. 

Report here: https://docs.google.com/document/d/1bPl1xfT5jylv0ntONCcfoa1MLOdsZHKzXcO1cjCauVA/edit#heading=h.t0vdk2nut12d

**Comment by Afollet** [comment]
@zperova I resolved all the mappings I changed yesterday. There is nothing for you to wait on here.

**Comment by zperova** [comment]
Great, thanks @Afollet and @mauroz77 
Report is very helpful!
Closing.
