### ISSUE TITLE
Update deployment script

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#469]
### Description

As a developer, I want to update deployment scripts to use Java 11 after it has been upgraded.

This can be done only when we know that we won't need any hot-fixes.

### Acceptance criteria

- [x] deployment scripts updated

**Comment by zperova** [comment]
on the day of the release.

**Comment by zperova** [comment]
Moving to the next sprint as needs to be done right before the release

**Comment by CsabaHalmagyi** [comment]
Updated beta deployment scripts.

**Comment by CsabaHalmagyi** [comment]
Done.
