### ISSUE TITLE
Migrate from Embassy-hosted Kubernetes to SPOT-hosted Kubernetes

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#481]
### Description

As a developer, I want to use the correct Kubernetes.

### Acceptance criteria

- [x] done

**Comment by Afollet** [comment]
Namespaces are created. However, I am debugging some errors in the pipelines to get them running

**Comment by Afollet** [comment]
Emailed www-prod about setting up ingress on pdx-validator-dev. I set up a nodePort to access the validator on pdx-validator. Continuous Integration pipelines that have bugs that need to be sorted out, but I am going to request to close this ticket in favor of data release work.

@zperova

**Comment by zperova** [comment]
thanks for the update @Afollet Closing this, please make the ticket for the bugs to be sorted (at a later time).
