### ISSUE TITLE
Estimates for tickets

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#484]
### Description

Please record real-time estimates for your tickets mentioned in this doc: https://docs.google.com/spreadsheets/d/1kalMMWe6Wt5rK3saJVE7aZTf10qYsaROeKdEuvCplGo/edit#gid=2136137018

Some tickets included did not have estimates when created, please enter the real-time it took if you remember. 

### Acceptance criteria

- [x] done by @Afollet 
- [x] done by @CsabaHalmagyi 
- [x] done by @mauroz77

**Comment by zperova** [comment]
This slipped my attention.
@CsabaHalmagyi please fill in the Real-time it took to finish the tasks when you have a chance: https://docs.google.com/spreadsheets/d/1kalMMWe6Wt5rK3saJVE7aZTf10qYsaROeKdEuvCplGo/edit#gid=1171784002

**Comment by CsabaHalmagyi** [comment]
I have done my part, too. Apologies for the delay.
