### ISSUE TITLE
Define schema for the new database

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#485]
### Description

As a developer, I want to define a schema for the new database. 

### Acceptance criteria

- [x] current templates converted into tables to promt discussion
- [x] meeting for discussion scheduled
- [x] schema agreed

**Comment by zperova** [comment]
we had 1 meeting, another meeting scheduled. Moving to the next sprint.

**Comment by zperova** [comment]
Had another meeting.

**Comment by zperova** [comment]
Needs another meeting with @Afollet 
Then another meeting with everyone

**Comment by Afollet** [comment]
I would like to table this until the next Sprint when we are not working on release tasks. @zperova

**Comment by zperova** [comment]
👍

**Comment by zperova** [comment]
moving to the next sprint

**Comment by Afollet** [comment]
This is the schema I would like to discuss with the team: https://app.diagrams.net/#G1pbQbcVCsX9BwT1b6S9A4KnF5gDnSCSNy

**Comment by zperova** [comment]
We have agreed that for the immediate needs this can be considered done. 
We can expand schema later on as needed.
