### ISSUE TITLE
Run validator on existing datasets

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#497]
### Description

As a developer, I want to have all the datasets according to the most recent template.

### Acceptance criteria

- [x] run validator on all datasets
- [x] list datasets that need change

**Comment by Afollet** [comment]
Here are the suspects. Error count/provider. The count is subject to change:
      1 provider [UMCG]
      2 provider [NKI]
      3 provider [Curie-BC]
      4 provider [Curie-LC]
      5 provider [Curie-OC]
      5 provider [IRCC-GC]
      6 provider [IRCC-CRC]
      6 provider [JAX-XDOG]
      6 provider [UOM-BC]
      6 provider [VHIO-BC]
      7 provider [LIH]
      7 provider [PMLB]
      7 provider [UOC-BC]
      7 provider [VHIO-CRC]
      9 provider [HCI-BCM]
     10 provider [VHIO-PC]
     12 provider [PDMR]
     12 provider [SJCRH]
     13 provider [CRL]
     14 provider [PPTC] 
     14 provider [WUSTL]
     17 provider [MDAnderson]
     18 provider [DFCI-CPDM]

**Comment by Afollet** [comment]
I created a document on how to use the validator with postman and some other details:
https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Posting+to+Validator+Microservice
I need to update the legal values for tumour_type, but the service is running.
@CsabaHalmagyi  @mauroz77

**Comment by Afollet** [comment]
@zperova done
