### ISSUE TITLE
Continuous Deployment for Pdx-Validator

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#498]
### Description
As a Developer, I want to easily deploy new changes.

Gitlab has been having unstable behaviors. I need to resolve or work around these errors to continue setting up both deployment instances of the pdx-validator.

Furthermore, the deployment method needs to be resolved. If Ingress is chosen, the configuration needs to be sorted with www-prod

### Acceptance criteria
- [x] CD runs for PDX-validator-dev
- [x] CD runs for PDX-validator
- [x] Networking options resolved and configured

**Comment by zperova** [comment]
This is dependent on the response from www-prod as well.

**Comment by Afollet** [comment]
I am in communications with WP-Admin about setting the configurations for the validator and pdx-gun.

**Comment by zperova** [comment]
this is now done
