### ISSUE TITLE
Migrate Continuous Deployment of PDX-Gun

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#499]
### Description

As a developer, I want to get continues deployment working on PDX-Gun for the MI kubernetes cluster to make deployment easy.

### Acceptance criteria
- [x] PDX-gun CD runs
- [x] PDX-gun-dev CD runs
- [x] Networking options are resolved (Nodeport or ingress)
- [x] main project reflects new microservice location

**Comment by Afollet** [comment]
I don't think it's worth the effort to migrate this service at the moment. It's a better use of time to try to get the service stable than to move the service.

As well, I would need to wait for www-prod for this to take place. I have contacted them, but I'm not certain I will get a response in a timely manner.

**Comment by zperova** [comment]
@Afollet please let me know if you don't hear anything back from them in a week's time

**Comment by Afollet** [comment]
I'm in contact with www-prod resolving the networking challenges with the pdx-gun currently.

**Comment by zperova** [comment]
was delayed due to SPOT-wide Kubernetes usage discussion. Picking up now, moving to the next sprint.

**Comment by Afollet** [comment]
Waiting on response form www-prod

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
response from www-prod has been slow, but it is in progress.

**Comment by Afollet** [comment]
prod has made the mapping to www.ebi.ac.uk/pdxfinder 

I just need to set it up and test it

**Comment by Afollet** [comment]
Done
