### ISSUE TITLE
Stats for EurOPDX portal publication

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#502]
### Description

As a developer, I want to know the following information to do some stats on the EurOPDX data in the PDX Finder.

How many and what are the fields collected in the metadata template that are accessible from the Portal?
How many "Essential" fields are filled out with "Not specified" per dataset/provider and what are those fields?
How many desirable fields are filled for the same dataset/provider and what are those fields?

### Acceptance criteria

- [x] Cypher queries run for EurOPDX and results are here: https://drive.google.com/drive/folders/12gs0BLP-8s2dIGv6NnX1-pKibkPnBNRv

**Comment by CsabaHalmagyi** [comment]
Emailed the data matrix to Zina.

**Comment by CsabaHalmagyi** [comment]
Cypher query used for this:
```
match (p:Patient)--(ps:PatientSnapshot)--(s:Sample)--(mod:ModelCreation) 
with p, ps, s, mod
match (s)--(tt:TumorType)
match (s)-[:ORIGIN_TISSUE]-(prs:Tissue)
match (s)-[:SAMPLE_SITE]-(ss:Tissue)
match (mod)--(qa:QualityAssurance)
optional match (p)--(pg:Group{type:"Provider"})
optional match (mod)--(ag:Group{type:"Accessibility"})
return distinct mod.dataSource, mod.sourcePdxId, p.externalId,p.sex, s.sourceSampleId, ps.ageAtCollection, s.diagnosis, tt.name, prs.name, ss.name, ps.treatmentNaive, qa.description, qa.passages, qa.technology, qa.validationHostStrain, ag.accessibility, ag.accessModalities, pg.providerType, pg.contact ORDER BY mod.dataSource

```
