### ISSUE TITLE
Downloadable recent templates from Submit/Contact page

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#503]
### Description

As a developer, I want to enable users to download a recent template from Submit/contact page.

### Acceptance criteria

- [x] solution is discussed and agreed upon
- [ ] solution is implemented

**Comment by zperova** [comment]
Can create a page in WP and upload the most recent templates there. This will need to be changed manually in case the templates have been updated. - This can be a temporary solution until we figure out a new front-end.

**Comment by CsabaHalmagyi** [comment]
Added the metadata link to the page:
https://cms.pdxfinder.org/get-in-touch-with-us/

Is there any additional changes in the text I need to do? @zperova

**Comment by CsabaHalmagyi** [comment]
@zperova could you have a look at the page? If you are happy with it I push it to prod and close this ticket.

**Comment by zperova** [comment]
@CsabaHalmagyi could you please change the title to "Download templates"? Can it be indicated somewhere that these are excel files, even if in the title and ideally the size of the file? or give an option of excel and tsv file? 

For the file names:
metadata_tamplate
sample_metadata_template
cytogenetics_template
mutation_template
CNA_template
fusion_template
expression_template

Thanks!

**Comment by zperova** [comment]
@CsabaHalmagyi to check with @Afollet on the most recent templates. Moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Uploaded the templates, the changes are available at:

https://cms.pdxfinder.org/get-in-touch-with-us/

(Initially the cna and expression template were failed to load due to some error in the mime type, so I converted them to xls and then back to xlsx to solve the problem)
