### ISSUE TITLE
Independent deployment of Admin UI frontend in Kubernetes

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#505]
### Description

As a developer, I want to deploy Admin UI front-end in Kubernetes.

### Acceptance criteria

- [x]  plan for separation
- [x]  implement
- [x] use separate repository for deployment

**Comment by mauroz77** [comment]
@zperova done.
UI:
- Dev: http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:31450/
- Prod: http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:31627/

More documentation: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/PDX+Admin
