### ISSUE TITLE
Remove Race from PDX Finder Patient details

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#511]
### Description

As a developer, I want to have field names in the PDX Finder that match what we are collecting in the metadata template to achieve consistency.

### Acceptance criteria

- [x] change "Race/Ethnicity" to "Ethnicity"

**Comment by Afollet** [comment]
I merged this to dev. Done.

@zperova

**Comment by zperova** [comment]
great, thanks @Afollet
