### ISSUE TITLE
Fix metadata for DFCI

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#540]
### Description

As a developer, I want to ensure correct metadata is represented in the PDX FInder.

### Acceptance criteria

- [x] metadata is cross-checked with provider
- [x] metadata updated

**Comment by zperova** [comment]
Received template here: https://docs.google.com/spreadsheets/d/18aTRtwpv1mp8YeqphCocO-B557vipir8/edit?usp=drive_web&ouid=110548651158605123831&rtpof=true

**Comment by zperova** [comment]
Original template here: https://docs.google.com/spreadsheets/d/1PvZIw2vT-HbEVX4QsyZInwxUuY91LSNu/edit?usp=drive_web&ouid=110548651158605123831&rtpof=true

**Comment by Afollet** [comment]
Done
