### ISSUE TITLE
Independent deployment of Admin UI back-end in Kubernetes

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#544]
###Description

As a developer, I want to deploy Admin UI back-end in Kubernetes.

###Acceptance criteria

- [x]  plan for separation
- [x]  implement
- [x] use separate repository for deployment

**Comment by zperova** [comment]
Need to figure out what to do with h2 db, to make the mappings work, as there is no indexer use in the future with using Spark. Need to figure out how to use Spark to make the mappings available.

**Comment by zperova** [comment]
Need to somehow save the mapping files as a safety belt.

**Comment by zperova** [comment]
moving to the next sprint

**Comment by mauroz77** [comment]
@zperova done. 
Api:

- Dev: http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:31450/

- Prod: http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:31627/

More documentation: https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/PDX+Admin
