### ISSUE TITLE
Make provider abbreviations links to provider pages on the Search page

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#553]
### Description

As a user, I want to have easy access to provider pages from the Search interface.

![Screenshot 2021-03-04 at 10.25.09.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/12aa2c4c-3411-4614-9af5-03d4d77cb660)

### Acceptance criteria

- [ ] provider abbreviations are links to provider pages

**Comment by zperova** [comment]
@CsabaHalmagyi please provide an estimate for this ticket

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Done.
