### ISSUE TITLE
Explore PCAT resource fro models and data to load

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#574]
### Description

As a developer, I want to load more pediatric models in the PDX Finder. 
PCAT resource: http://www.pedtranscriptome.org/
Publication: https://pubmed.ncbi.nlm.nih.gov/32810235/

### Acceptance criteria

- [x] new models and data to load to PDX Finder identified

**Comment by zperova** [comment]
@Csaba to update estimate based on required effort. Currently : 8

**Comment by CsabaHalmagyi** [comment]
[https://app.zenhub.com/files/78657127/6680f920-5ae3-4f31-a211-59b96541d9d1/download](https://app.zenhub.com/files/78657127/6680f920-5ae3-4f31-a211-59b96541d9d1/download)
