### ISSUE TITLE
Extend the validator for the sample platform template

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#580]
### Description

As a developer, I want to have automatic validation for the sample platform template.

### Acceptance criteria

- [x] context and syntax validation in place
- [x] command line interface extended

**Comment by zperova** [comment]
@zperova this should go into the new epic for all the templates

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
moving to the next sprint

**Comment by zperova** [comment]
Pausing this in preference for Data loading for the June release

**Comment by Afollet** [comment]
@CsabaHalmagyi  done
