### ISSUE TITLE
Refactor Validator for Scalability

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#604]
As a developer I need the validator to scale to allow for better readability and maintenance. This requires the rules to be expressed in a format like yaml and parsed by the validator. 

### Acceptance criteria: 
- [x] code is written
- [x] tests are written
- [x] changes are deployed

**Comment by zperova** [comment]
Pausing this in preference for Data loading for Release in June

**Comment by Afollet** [comment]
@CsabaHalmagyi  Done
