### ISSUE TITLE
Load PMLB Pancreas data

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#605]
As a PDX Finder User I  would like all available data published to the database

PMLB Pancreatic data is ready to publish.

###### ACCEPTANCE CRITERION ######

- [x] data is validated
- [x] cbioportal data is retrieved and transformed
- [x] data is pushed to dev
- [x] wordpress pages are updated and checked as needed.

**Comment by Afollet** [comment]
Metadata has been validated and is on dev. There are twelve mappings that are currently needed.

**Comment by zperova** [comment]
@zperova to do the mappings

**Comment by Afollet** [comment]
Done
