### ISSUE TITLE
Check that JAX dataset is still up-to-date

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#648]
### Description

As a developer, I want to make sure the JAX dataset is up-to-date.

Use API to get the data, cross-check with what is currently in the PDX FInder in relation to drug dosing.

### Acceptance criteria

- [x] done
- [x] if new models - make ticket to map the new data

**Comment by CsabaHalmagyi** [comment]
- Updated jax script for data download
- Downloaded new dataset
- Test load done

Need to do one more testload to cross reference check drug dosing
