### ISSUE TITLE
Define minimal feature requirements for the API for Nov 2021 release

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#650]
### Description

As a developer, I want to know the minimal requirements for the API to start planning the required work.

### Acceptance criteria

- [x] make a summary of what PDX Finder already offers
- [ ] meeting scheduled
- [ ] document with minimal feature requirements for the Nov release

**Comment by zperova** [comment]
The summary will be in a format of a table describing a feature with the level of priority and any comments if needed.

**Comment by CsabaHalmagyi** [comment]
Created a document with the current features of the pdxfinder:

https://docs.google.com/spreadsheets/d/1bOpTRBDAIyhRsVVmI5qFQxHmdr7vYXkMAO_dZ7NVywU/edit?usp=sharing

**Comment by zperova** [comment]
Prioritize the features for implementation

**Comment by zperova** [comment]
moving to the next sprint

**Comment by CsabaHalmagyi** [comment]
Priorities were set by @zperova in the document, planning accordingly.
