### ISSUE TITLE
Search page for the PDCM resource

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#654]
### Description

As a developer, I want to have a Search page for the PDCM resource.

### Acceptance criteria

- [ ] search results table
- [ ] search bar 
- [ ] pagination
- [ ] search filter
- [ ] current query display
- [ ] done

**Comment by ficolo** [comment]
In progress:

- Whole page: https://pdxfinder.github.io/pdcm-web-ui/?path=/story/pages-search--default
- Search results table: https://pdxfinder.github.io/pdcm-web-ui/?path=/story/components-search-results-table--default
- Search bar: https://pdxfinder.github.io/pdcm-web-ui/?path=/story/components-filter-search-bar--default
