### ISSUE TITLE
API URL design pattern

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#664]
### Description

As a developer, I want to know the API URL design pattern to implement it.

Will this be a REST API?

### Acceptance criteria

- [x] Google spreadsheet with url space
- [x] schedule a meeting to discuss

**Comment by jmason-ebi** [comment]
Working document :  https://docs.google.com/spreadsheets/d/1x0JwYt6j2VOL-gtMq4u0eIwA9aMKBKS-vjUNeTOzvy4/edit#gid=0

This is a live document, but we have agreed upon the basic structure and breakdown
