### ISSUE TITLE
Implement logic for assignation of raw_data_url

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#666]
As a developer, I want to assign the correct raw_data_url for a PATIENT_SAMPLE based on the field raw_data_file in the template sampleplatform.

Take as reference: https://github.com/PDXFinder/pdxfinder/blob/master/indexer/src/main/java/org/pdxfinder/dataloaders/updog/domainobjectcreation/DomainObjectCreator.java#L304

### Acceptance Criteria ### 

- [x] TransformPatientSample class generates the data in the expected format

**Comment by mauroz77** [comment]
Currently the applied logic takes the data from raw_data_file in [provider]sampleplatform and formats it into the adequate url if it matches any of the following regular expressions:

^PRJ[EDN][A-Z][0-9]{0,15}$
^[EDS]R[SXRP][0-9]{6,}$
^EGA[A-Za-z0-9]+$
^GSM[A-Za-z0-9]+$

What happens with data that does not match that format?

Example of raw_data_file in CRL_sampleplatform:
![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/4baf76b4-6110-44e5-b107-88ae591b03ff)

**Comment by Afollet** [comment]
They get flushed, mate

**Comment by mauroz77** [comment]
@zperova done
