### ISSUE TITLE
Fix PPTC name on the landing page

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#673]
**Describe the bug**

**To Reproduce**
1. Go to landing page
2. Scroll down to Providers

**Expected behavior**
Pediatric Preclinical Testing Consortium

**Screenshots**
![Screenshot 2021-06-02 at 11.21.18.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/bc96297e-3c30-4353-90bb-0369a058a039)

**Comment by CsabaHalmagyi** [comment]
1. Updated the data in the template.
2. Manually updated the value on beta and on both prod vms without triggering a release.
