### ISSUE TITLE
Fix provider abbreviation for University of Manchester Breast Centre

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#674]
**Describe the bug**

**To Reproduce**
1. Go to https://www.pdxfinder.org/source/uom-bc/
2. See error

**Expected behavior**
The title should be "University of Manchester Breast Centre" and the button to search for models should say "UOM-BC" - as this is the abbreviation we use.

**Screenshots**
![Screenshot 2021-05-13 at 16.17.23.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/4712f174-beb2-4d80-827c-790c97f12b90)

![Screenshot 2021-05-13 at 16.17.28.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/d9d8dbe8-3f5f-47c0-a391-fc884e540d8a)

**Comment by CsabaHalmagyi** [comment]
Updated button and main text.

**Comment by CsabaHalmagyi** [comment]
Pushed to prod. Done.
