### ISSUE TITLE
Update PDX Relation Diagram Names

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#685]
The variable names used in the ETL should match the names used in the data collection templates.

######### ACCEPTANCE CRITERION ##########
- [x] Names are updated and higlighted in diagram
- [ ] the changes are reflected in the code base.

**Comment by Afollet** [comment]
@mauroz77 

Please confirm the changes:
https://app.diagrams.net/#G1AQV4mZjbZ3e4ClBZ4ezY9X75GDki8b0T

In the yellow are the name changes. In most cases I went with what is written on the templates for consistency.

Engraftment_material is sample_type on the collection template. This is  a confusing mapping, but it would also be confusing to use the term "sample_type" in the specimen table because there are a few contexts that use "sample". Therefore, I renamed it in the the db to engraftment_sample_type. I'm not completely convinced about this because the naming is odd, but it is far more costly to change the templates than the db and this naming convention will be easier to mentally map between the db and templates.

In the red are points of interest. I added the "engrafment_sample_state" and associated table it references to the Specimen table. It's in the metadata, but not currently read into the database. This is the same thing to the "prior_treatment" column in the Patient_Sample table

**Comment by mauroz77** [comment]
@Afollet proposed changes look clear. I'll assign the ticket to me now to update existing code

**Comment by mauroz77** [comment]
@Afollet should we also make in this ticket the renaming from internal to external ids when needed or do you see that as a separated ticket?

**Comment by Afollet** [comment]
Yeah, I agree. I think it would be a good idea to make the changes you mentioned in the edit.

**Comment by CsabaHalmagyi** [comment]
Done.
