### ISSUE TITLE
Update ETL with updates in database diagram

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#686]
As a developer I want to have the ETC code aligned with the design of the entities in https://drive.google.com/drive/folders/1iOqUVbLx3nVav3boE21EYTYCFniU8COt

## Acceptance Criteria ##
- [x] ETL has the updated names in the code and generated database

**Comment by mauroz77** [comment]
Done. @CsabaHalmagyi existing code in ETL was already updated with the changes in the document.

**Comment by CsabaHalmagyi** [comment]
Done.
