### ISSUE TITLE
Populate static content in raw data store

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#718]
As a developer I want to retire WP and create a sustainable way to store and retrieve static content

Static content and platform pages need to be processed into the appropriate files in the git data repo.

####### ACCEPTANCE CRITERIA #######
- [x] Static content create and place into template
- [x] platform pages have been fit into the two sections of the platform_web workbook
- [x] all images are in web folder
- [x] loader tsv is retired
- [x] provider_name, provider_abbreviation and project are removed from metadata.xlsx workbooks

**Comment by Afollet** [comment]
- [] ./CRL
- [] ./IRCC-CRC
- [] ./PPTC
- [] ./NKI
- [] ./UOC-BC
- [] ./JAX
- [] ./PMLB
- [] ./LIH
- [] ./UOM-BC
- [] ./Curie-LC
- [] ./IRCC-GC
- [] ./PDMR
- [] ./SJCRH
- [] ./WUSTL
- [] ./Wistar-MDAnderson-Penn
- [] ./VHIO-PC
- [] ./VHIO-CRC
- [] ./VHIO-BC
- [] ./UMCG
- [] ./TRACE
- [] ./MDAnderson
- [] ./HCI-BCM
- [] ./DFCI-CPDM
- [] ./Curie-OC
- [] ./Curie-BC

**Comment by Afollet** [comment]
Dosing studies have platform pages, but they were never included in the "sampleplatform" workbooks. A decision on how these should be handled needs to be made.

**Comment by Afollet** [comment]
These providers do no have logo images
{'CMP',
 'Curie-BC',
 'Curie-LC',
 'Curie-OC',
 'HCI-BCM',
 'MDAnderson',
 'WUSTL',
 'Wistar-MDAnderson-Penn'}

**Comment by Afollet** [comment]
[https://app.zenhub.com/files/78657127/365ca064-92ed-4c31-a4a8-e16bc1eb6c9a/download](https://app.zenhub.com/files/78657127/365ca064-92ed-4c31-a4a8-e16bc1eb6c9a/download)

**Comment by Afollet** [comment]
Static content is provided in the source.yaml, logo.png, and the molecular-metadata-platform-web.tsv sheet. The former two are placed in the web content directory of every provider ( some do not have logo's)

**Comment by Afollet** [comment]
Jax will need to be placed on a separate ticket for correspondence

**Comment by Afollet** [comment]
@CsabaHalmagyi done. I need to make a ticket for JAX

**Comment by CsabaHalmagyi** [comment]
Done
