### ISSUE TITLE
Explore organoid/cell line data ingestions

### ISSUE THREAD

**Issue by Afollet** [PDXFinder/pdxfinder#719]
As a developer, I want to be able to expand the PDCM model to organoids and cell lines as efficiently as possible

############# ACCEPTANCE CRITERION #############
- [x] Data has been mapped
- [x] updated template has been designed
- [x] updates have been implemented in data repo

**Comment by Afollet** [comment]
Notes on the discussion about integrating the Cell Model Passport :
https://docs.google.com/document/d/1IEIGslJaUtEtKihdJgvFl8k-IeefYwgfwYgzMAumKbU/edit?usp=sharing

I am going to proceed to make a prototype template.

**Comment by Afollet** [comment]
Added the cell and organoid model templates to the repo template/templates_1.0.0/cell_and_organoid_metadata_template.xlsx

**Comment by Afollet** [comment]
[https://app.zenhub.com/files/78657127/913ce4db-7d29-4746-82ca-3e5510cd3232/download](https://app.zenhub.com/files/78657127/913ce4db-7d29-4746-82ca-3e5510cd3232/download)

**Comment by Afollet** [comment]
@CsabaHalmagyi Done.

**Comment by CsabaHalmagyi** [comment]
Done
