### ISSUE TITLE
Change copy to database task to copy tables individually

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#728]
As a developer I want the ETL to be able to use multiple cores when available so having more granular tasks can help with that. The current copy task copies all the csvs with the formatted data into the database at once, and some tables are bigger than others. We should see an improvement in performance if we have a copy task by table so multiple tables can be copied in parallel.

**Comment by mauroz77** [comment]
@CsabaHalmagyi done

**Comment by CsabaHalmagyi** [comment]
Done
