### ISSUE TITLE
Update Jax data 

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#831]
### Description

As a developer, I want to ensure all the data is available in PDCM Finder beta release.

### Acceptance criteria

- [x] Jax data uploaded and released

**Comment by zperova** [comment]
moving to the next sprint. @Mandloi2309 to contact Steve about this

**Comment by Mandloi2309** [comment]
Found the missing information in the raw data file. Contacting Steve not required. Done @zperova
