### ISSUE TITLE
View Data at [Provider] button missing or broken

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#891]
Make View Data at [Provider] button available for the following providers:
Missing:
- [x] Curie-BC : general link https://institut-curie.org/plateforme/curiecoretech-vivo-preclinical-experiments
- [x] Curie-LC : general link https://institut-curie.org/plateforme/curiecoretech-vivo-preclinical-experiments
- [x] Curie-OC : general link https://institut-curie.org/plateforme/curiecoretech-vivo-preclinical-experiments
- [x] HCMI : https://hcmi-searchable-catalog.nci.nih.gov/
- [x] IRCC-CRC: general link https://www.irccs.com/en/who-we-are
- [x] IRCC-GC: general link https://www.irccs.com/en/who-we-are
- [x] LIH : https://www.lih.lu/en/research-scope/research-department/department-of-cancer-research/norlux-neuro-oncology-laboratory/
- [x] MDAnderson: https://www.pdxnetwork.org/md-anderson
- [x] NKI : https://www.nki.nl/research/facilities-platforms/animal-facility-mouse-cancer-clinic/
- [x] UMCG : https://www.rug.nl/research/oncology/
- [x] UOC-BC : https://caldaslab.cruk.cam.ac.uk/bcape/
- [x] UOM-BC : http://www.breastcentre.manchester.ac.uk/
- [x] VHIO-BC : general https://www.vhio.net/
- [x] VHIO-CRC : general https://www.vhio.net/
- [x] VHIO-PC : general https://www.vhio.net/
- [x] Wistar-MDAnderson-Penn : https://www.pdxnetwork.org/the-wistarmd-andersonpenn
- [x] WUSTL : https://www.pdxnetwork.org/wustl

Broken:
- [x] PDMR - general link: https://pdmdb.cancer.gov/web/apex/f?p=101:41
- [x] TRACE : https://gbiomed.kuleuven.be/english/research/50488876/54502087/Trace/PDX-repository

**Comment by zperova** [comment]
please also check that the link for Wistar and HCI points to their PDXNet page

**Comment by Mandloi2309** [comment]
HCI points to pdxnet,
HCMI-BCM: models with no link point to GDC page: https://portal.gdc.cancer.gov/projects/HCMI-CMDC

**Comment by Mandloi2309** [comment]
done
