### ISSUE TITLE
View data button not functional

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#895]
**Describe the bug**
View data button not functional in the Molecular data table

**To Reproduce**
1. Go to https://www.cancermodels.org/#/data/IRCC-CRC/CRC0021LM
2. Scroll down to Molecular data
4. See greyed out View data

**Expected behavior**
View data is clickable and opens data for all available data in the db

**Screenshots**
![Screenshot 2022-04-13 at 23.06.14.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/fa963d42-7a5c-4f4d-a284-fdfa9123a97e)
**Additional context**

This is not the only model that is affected by this issue.

**Comment by ficolo** [comment]
The data is not available on the database because is not available on the TSV file, the TSV file looks like this currently:

https://gitlab.ebi.ac.uk/mouse-informatics/pdxfinder-data/-/blob/dev/data/UPDOG/IRCC-CRC/cna/targetted_ngs/IRCC-CRC_cna_ngs.tsv

**Comment by zperova** [comment]
Investigate why no data is there

**Comment by zperova** [comment]
This particular dataset has been removed. Need to put a note to contact th eprovider for this data - this needs a separate ticket. @zperova

**Comment by zperova** [comment]
duplicate
