### ISSUE TITLE
Data not being displayed in the Web UI

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#896]
**Describe the bug**
Data is not displayed even though it is in the database. 

**To Reproduce**
1. Go to https://www.cancermodels.org/#/data/PMLB/OCIP026
2. Scroll down to View data
4. See greyed out View data

**Expected behavior**
Data is visible.

**Screenshots**
![Screenshot 2022-04-20 at 15.21.46.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/8ab2bd66-7bda-44da-b94d-b831c315d46f)

**Additional context**
This might be for more than PMLB data.
This is likely an ETL issue.

**Comment by zperova** [comment]
@ficolo to generate a list of all the instances where the data is not visible

**Comment by ficolo** [comment]
Change grey button for a message saying something like "this data is not available on the finder please go to the provider"

**Comment by zperova** [comment]
This is a duplicate ticket: https://app.zenhub.com/workspaces/pdcmfinder-board-5f0f036188f27e0014a7bdfc/issues/pdcmfinder/pdxfinder/895

**Comment by zperova** [comment]
@Mandloi2309 could you please check these specific cases for how the raw data looks like to figure out whether this is a data or ETL problem. Thank you!

**Comment by zperova** [comment]
closing this one and will open specific for data clean-up. This particular case should be fixed after release.
