### ISSUE TITLE
Evaluate current state of the pdx Admin functionality

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#902]
As a developer I want to have a clear vision of what the pdx admin functionality offers and how it could be improved

## Acceptance Criteria ## 
- [ ] Document(s) describing current state of the application
- [ ] Meetings to discuss about current issues and potential solutions

**Comment by zperova** [comment]
https://drive.google.com/drive/folders/1QYqlgASgkzMEmjkz2-c-MQGVryZ3n4Py

**Comment by zperova** [comment]
@zperova make this an Epic and split into smaller tasks
