### ISSUE TITLE
Clean up PPTC metadata - change to PIVOT

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#914]
### Description

PPTC is not PIVOT: http://www.ncipptc.org/
Reflect this change in the PDXFinder and PDCM Finder:
Description: https://www.pdxfinder.org/source/pptc/
Provider name, website, contact info: https://www.pdxfinder.org/data/search?datasource=PPTC

### Acceptance criteria

- [x] Provider name changed
- [x] Description changed
- [x] contact person changed

**Comment by Mandloi2309** [comment]
Added link to the contact form on PIVOT's website

**Comment by Mandloi2309** [comment]
done
