### ISSUE TITLE
[Website] Expose DEV environment under dev.cancermodels.org

### ISSUE THREAD

**Issue by ficolo** [PDXFinder/pdxfinder#918]
- [x] Check that the DEV k8s deployment meets the requirements from WP for being exposed outside of the EBI network.

- [x] Ask WP to create a subdomain dev.cancermodels.org and ask them to setup LB rules to expose the NodePort service.

**Comment by zperova** [comment]
waiting to hear from Web production team on this

**Comment by zperova** [comment]
might need a new ticket due to move to ServiceNow
