### ISSUE TITLE
Create mechanism to migrate existing rules to new db structure

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#926]
As a developer, I want to be able to migrate the existing mapping rules to the new db representation taking into account the new database schema

## Acceptance Criteria
- [ ] Endpoint created to load in the db existing rules (with the old format)

**Comment by mauroz77** [comment]
As a developer, I want to be able to migrate the existing mapping rules to the new db representation taking into account the new database schema

- [ ] Endpoint created to load in the db existing rules (with the old format)
- [ ] Create an endpoint in pdx-admin-backend to allow creation of json file with rules with all the status

**Comment by zperova** [comment]
done
