### ISSUE TITLE
Merge PDCMFinder-data 'dev' with 'master' branch

### ISSUE THREAD

**Issue by Mandloi2309** [PDXFinder/pdxfinder#933]
### Description

As a developer, I want to merge the dev branch with master branch after the PDCM data release.

### Acceptance criteria

- [x] done

**Comment by zperova** [comment]
@Mandloi2309 to clean up the existing branches and document in Confluence

**Comment by Mandloi2309** [comment]
Merged the dev branch with release tag (https://gitlab.ebi.ac.uk/mouse-informatics/pdxfinder-data/-/commit/00f468210a23d81ec4c3eb42a1d2300fc1b45ab2). Removed the stale branches PDCM_DR_1.0 (This was the data release branch, now merged with master), CI_test, and Annotations as they were stale and were used for setting up the CI/CD and storing annotation zip files respectively.
