### ISSUE TITLE
Review Mixed Glioma case

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#944]

**Comment by mauroz77** [comment]
Mixed Glioma is a diagnosis used in CMP. The term can be found in OLS http://purl.obolibrary.org/obo/NCIT_C3903, but it is not loaded in our internal ontology table. This is because that term is not a children of Malignant Neoplasm (even when an alt description is: "A malignant neoplasm comprising two or more glial cell types (e.g., astrocytes, ependymal cells, oligodendrocytes)".

We need to decide how to handle that scenario

**Comment by zperova** [comment]
done
