### ISSUE TITLE
Identify cases where VIEW DATA is not functional or a common reason 

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#971]
### Description

As a user, I want to be able to view all available data for the models.

### Acceptance criteria

- [x] all cases identified
- [x] reason(s) determined
- [x] solution planned

**Comment by Mandloi2309** [comment]
1. Host strain name not visible for PIVOT models: https://www.cancermodels.org/data/models/PIVOT/ES-6
2. Copy number data for IRCC-CRC targeted NGS: (molecular data removed).
3. Mutation data from MISEq platform for LIH not visible.
4. mutation data for few samples in PDMR not visible. (https://www.cancermodels.org/data/models/PDMR/241356-047-R): (no molecular data available)

**Comment by Mandloi2309** [comment]
above mentioned issues should get fixed with the next release
