### ISSUE TITLE
Fix host mouse strain nomenclature

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#981]
### Description

As a user, I want to see correct host mouse strain nomenclature in the PDCM Finder.

### Acceptance criteria

- [x] make the following changes to all templates:  bracket parts that should be in superscript. Example:

NOD.CB17-Prkdcscid/J change to NOD.CB17-Prkd<cscid>/J

**Comment by Mandloi2309** [comment]
done
