### ISSUE TITLE
Move all static content to md

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#983]
### Description

As a developer, I want to have all static content in markdown for consistency and ease of updates.
Pages:
 About button:
- PDCM Finder
- Privacy policy
- Terms of use
- Model providers

Footer:
- Submit models
- Feedback

### Acceptance criteria

- [ ] all static pages are moved to md

**Comment by mriios** [comment]
Also create `.md` files for each provider, eg `/about/provider/JAX`
