### ISSUE TITLE
Make necessary changes in the ETL for the treatment response filter

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#984]
### Description

As a developer, I want consistent working of the filter - the treatment response filter should be working as the gene mutation filter

### Acceptance criteria

- [x] ETL changes implemented
- [x] run ETL (possibly only the Search index part)

**Comment by ficolo** [comment]
https://docs.google.com/document/d/1j1TQf02fka-TK-K5pmi4PnU7M8gDuBLUL_198-vuCWQ/edit#

**Comment by ficolo** [comment]
https://github.com/PDCMFinder/pdcm-etl/blob/master/etl/jobs/transformation/search_index_transformer_job.py#L240

**Comment by mauroz77** [comment]
@zperova moving to review. This is applied in dev so you should be able to check the changes.

**Comment by zperova** [comment]
@mauroz77 thank you I have checked on dev, and I can see that my proposed forward slash looks confusing, especially taken the length of the total string. What do you think about replacing the second forward slash with = ?
So that it looks like this:
cetuximab/encorafenib regimen=Progressive Disease

**Comment by zperova** [comment]
@mauroz77 what is the status of this ticket, please? looks like changes have been implemented in dev, I am not sure about the second acceptance criteria. thanks

**Comment by mauroz77** [comment]
@zperova this is already implemented and deployed in dev. Only missing the deploy in prod which is basically the release we are planning for next week
