### ISSUE TITLE
Remove Not Collected and Not provided filter for Tumor type in filter box

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#988]
### Description

Currently, values for Tumor type filter contain Not Collected and Not provided values.

![image.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/ed8f44ab-16b2-487f-94af-dd4fb5ee844c)

We agreed this change is more appropriate to be done in the ETL instead of the UI.
The proposed solution is to modify the search_facet transformation to exclude Not Collected/Not Provided from the values in Tumor type.

### Acceptance criteria

- [x] Filter does not include Not Collected/Not Provided.

**Comment by zperova** [comment]
this needs to be done at the level of ETL - needs discussion

**Comment by mauroz77** [comment]
@zperova done
