### ISSUE TITLE
Fix pk_xenograft_model_specimen error

### ISSUE THREAD

**Issue by mauroz77** [PDXFinder/pdxfinder#991]
Error when running the ETL with all providers:

psycopg2.errors.UniqueViolation: could not create unique index "pk_xenograft_model_specimen"
DETAIL:  Key (id)=(1554778161163) is duplicated.

**Comment by mauroz77** [comment]
@Mandloi2309 https://gitlab.ebi.ac.uk/mouse-informatics/pdxfinder-data/-/blob/dev/data/UPDOG/HCI-BCM/HCI-BCM_metadata-sharing.tsv#L57 this line has a model id (HCI-008) that already exists. This is the real cause of the issue, not what I said before about a model with different host_strains in metadata-pdx_model

**Comment by zperova** [comment]
this will be solved by updating Validator rules
